'use strict';
const NS='http://www.w3.org/2000/svg';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const TEXT_TYPES=['text','textbox','note'];
const BOX_TYPES=['rect','square','ellipse','circle','cloud','hatch','highlight','textbox','note','stamp','trafficSign','device'];
const LINE_TYPES=['line','arrow','measure','callout','deviceRun'];
const POLY_TYPES=['polygon','polyline','cloudFree','hatchFree'];
const state={tool:'hand',previousTool:null,zoom:1,pages:[],pageIndex:0,selected:null,drawing:null,pan:null,projectName:'Untitled Plan',polyDraft:null,editing:null,propertyMode:'object',propertyTool:null,customStamps:[],pdfDoc:null,pdfBytes:null,pdfFileName:null,pdfRenderToken:0,mutcdIndex:null,mutcdLoad:null,clipboard:null,history:[],future:[],restoring:false,layers:[{id:'default',name:'Default',visible:true,locked:false},{id:'comments',name:'Review / Comments',visible:true,locked:false},{id:'traffic',name:'Traffic Control',visible:true,locked:false},{id:'measurements',name:'Measurements',visible:true,locked:false}],activeLayer:'default',preset:{stroke:'#d71920',width:2,fill:'#ffffff',fillOpacity:0,dash:'',hatch:'none',hatchColor:'#d71920',hatchSpacing:10,opacity:1,rotation:0,font:'Arial',fontSize:14,textColor:'#111111',textAlign:'left',bold:false,italic:false}};
const inspection=['FIELD VISIT PENDING','FIELD VISIT REQUIRED','FIELD INSPECTION REQUIRED','PASSED INSPECTION','PASSED PRE-POUR INSPECTION','PASSED PRE-PAVE INSPECTION','REINSPECTION REQUIRED','CORRECTIONS REQUIRED','FIELD VERIFIED'];
const signals=['SIGNAL INSPECTION REQUIRED','SIGNAL INSPECTION PASSED','SIGNAL INSTALLATION PENDING','SIGNAL INSTALLATION VERIFIED','SIGNAL ACTIVATION PENDING','SIGNAL WORK REQUIRES CORRECTION'];
const signs=['SIGN INSPECTION REQUIRED','SIGN INSTALLATION VERIFIED','SIGN PLACEMENT CORRECTION REQUIRED','SIGN MISSING','SIGN RELOCATION REQUIRED','SIGN REPLACEMENT REQUIRED'];
const ttc=['TTC INSPECTION REQUIRED','TTC APPROVED','TTC CORRECTION REQUIRED','TTC SETUP VERIFIED','TTC REVISION REQUIRED','DEVICE PLACEMENT CORRECTION REQUIRED','MISSING TTC DEVICE','BARRICADE / CHANNELIZING DEVICE CORRECTION','TRAFFIC CONTROL NOT PER PLAN','TRAFFIC CONTROL FIELD ADJUSTMENT REQUIRED'];
const PDF_ASSET_BASE='./vendor/pdfjs/';
const MUTCD_ASSET_BASE='assets/Signs SVGs/mutcd-svg-main/';
let pdfjsLib=null;
async function ensurePdfJs(){
 if(pdfjsLib)return pdfjsLib;
 Promise.try ||= ((fn,...args)=>Promise.resolve().then(()=>fn(...args)));
 Uint8Array.prototype.toHex ||= function(){return Array.from(this,b=>b.toString(16).padStart(2,'0')).join('')};
 Uint8Array.fromHex ||= function(hex){const a=new Uint8Array(Math.floor(hex.length/2));for(let i=0;i<a.length;i++)a[i]=parseInt(hex.slice(i*2,i*2+2),16);return a};
 Map.prototype.getOrInsertComputed ||= function(key,fn){if(this.has(key))return this.get(key);const v=fn(key);this.set(key,v);return v};
 URL.parse ||= function(url,base){try{return new URL(url,base)}catch{return null}};
 pdfjsLib=await import(new URL(PDF_ASSET_BASE+'pdf.mjs',location.href).href);
 pdfjsLib.GlobalWorkerOptions.workerSrc=new URL(PDF_ASSET_BASE+'pdf.worker.wrapper.mjs',location.href).href;
 return pdfjsLib;
}
function pdfOptions(data){return{data:new Uint8Array(data),cMapUrl:new URL(PDF_ASSET_BASE+'cmaps/',location.href).href,cMapPacked:true,standardFontDataUrl:new URL(PDF_ASSET_BASE+'standard_fonts/',location.href).href,wasmUrl:new URL(PDF_ASSET_BASE+'wasm/',location.href).href,iccUrl:new URL(PDF_ASSET_BASE+'iccs/',location.href).href,useWorkerFetch:false}}
function bytesToBase64(bytes){let out='',step=0x8000;for(let i=0;i<bytes.length;i+=step)out+=String.fromCharCode(...bytes.subarray(i,Math.min(bytes.length,i+step)));return btoa(out)}
function base64ToBytes(s){const b=atob(s),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a}
async function loadPdfBytes(bytes,name,pagesOverride=null){
 const lib=await ensurePdfJs();
 state.pdfBytes=new Uint8Array(bytes);state.pdfFileName=name||'Imported.pdf';
 const task=lib.getDocument(pdfOptions(bytes));state.pdfDoc=await task.promise;
 const pages=[];
 if(Array.isArray(pagesOverride)){
  // Preserve the saved NXT page order exactly. This is important after deleting,
  // duplicating, rotating, or mixing PDF pages with blank/image sheets.
  for(const saved of pagesOverride){
   const prior=JSON.parse(JSON.stringify(saved));
   if(prior?.source?.type==='pdf'){
    const pn=Math.max(1,Math.min(state.pdfDoc.numPages,Number(prior.source.pageNumber)||1));
    const pg=await state.pdfDoc.getPage(pn),rot=Number(prior.rotation)||0,vp=pg.getViewport({scale:1,rotation:rot});
    prior.source={type:'pdf',pageNumber:pn};prior.w=vp.width;prior.h=vp.height;
   }
   prior.id=prior.id||uid();prior.markups=Array.isArray(prior.markups)?prior.markups:[];pages.push(prior);
  }
 }else{
  for(let i=1;i<=state.pdfDoc.numPages;i++){
   const pg=await state.pdfDoc.getPage(i),vp=pg.getViewport({scale:1,rotation:0});
   pages.push({id:uid(),w:vp.width,h:vp.height,name:`PDF Page ${i}`,bg:null,source:{type:'pdf',pageNumber:i},rotation:0,markups:[]});
  }
 }
 state.pages=pages;state.pageIndex=0;state.selected=null;state.projectName=name||state.projectName;state.history=[];state.future=[];render();requestAnimationFrame(fitPage);
}
function snapshotState(){return JSON.stringify({pages:state.pages,layers:state.layers,activeLayer:state.activeLayer,preset:state.preset,projectName:state.projectName})}
function checkpoint(){if(state.restoring)return;const snap=snapshotState();if(state.history.at(-1)!==snap){state.history.push(snap);if(state.history.length>60)state.history.shift()}state.future=[]}
function restoreSnapshot(str){state.restoring=true;const d=JSON.parse(str);state.pages=d.pages;state.layers=d.layers;state.activeLayer=d.activeLayer;state.preset=d.preset;state.projectName=d.projectName;state.pageIndex=Math.min(state.pageIndex,state.pages.length-1);state.selected=null;state.restoring=false;render()}
function undo(){if(!state.history.length)return toast('Nothing to undo.');state.future.push(snapshotState());restoreSnapshot(state.history.pop());toast('Undo')}
function redo(){if(!state.future.length)return toast('Nothing to redo.');state.history.push(snapshotState());restoreSnapshot(state.future.pop());toast('Redo')}

function uid(){return 'm'+Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function newPage(w=792,h=612,name='ANSI A Landscape'){return{id:uid(),w,h,name,bg:null,markups:[]}}
state.pages=[newPage()];
function currentPage(){return state.pages[state.pageIndex]}
function selectedMarkup(){return currentPage()?.markups.find(m=>m.id===state.selected)||null}
function layerById(id){return state.layers.find(l=>l.id===(id||'default'))||state.layers[0]}
function isMarkupVisible(m){return layerById(m.layer).visible!==false}
function isMarkupLocked(m){return !!m.locked||!!layerById(m.layer).locked}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');clearTimeout(t._tm);t._tm=setTimeout(()=>t.classList.add('hidden'),2600)}
function toolLabel(t){return({hand:'Hand',select:'Select',zoom:'Marquee Zoom',textselect:'Text Select',rect:'Rectangle',square:'Square',ellipse:'Ellipse',circle:'Circle',polygon:'Polygon',polyline:'Polyline',line:'Line',arrow:'Arrow',freehand:'Pen',highlight:'Highlight',cloud:'Cloud Box',cloudFree:'Freeform Cloud',hatch:'Hatch Box',hatchFree:'Freeform Hatch',text:'Text Line',textbox:'Text Box',note:'Note Box',callout:'Callout',measure:'Measure',deviceRun:'Device Run'})[t]||t}
function setTool(tool){if(state.polyDraft&&state.tool!==tool)finishPolyDraft(false);state.tool=tool;$$('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));$('#statusTool').textContent=toolLabel(tool);$('#canvasScroller').style.cursor=tool==='hand'?'grab':tool==='zoom'?'crosshair':tool==='textselect'||TEXT_TYPES.includes(tool)?'text':'crosshair';$('#pageStage').classList.toggle('textSelect',tool==='textselect');const tl=$('#pdfTextLayer');if(tl)tl.classList.toggle('active',tool==='textselect')}
function style(){return JSON.parse(JSON.stringify(state.preset))}
function render(){const p=currentPage(),svg=$('#pageSvg');if(!p)return;svg.setAttribute('viewBox',`0 0 ${p.w} ${p.h}`);const sc=96/72*state.zoom;svg.style.width=p.w*sc+'px';svg.style.height=p.h*sc+'px';$('#pageStage').style.width=svg.style.width;$('#pageStage').style.height=svg.style.height;$('.paper').setAttribute('width',p.w);$('.paper').setAttribute('height',p.h);renderBackground();renderMarkups();renderPages();renderTable();updateStatus();updateProperties();renderPdfUnderlay();if(state.editing)positionInlineEditor()}
function renderBackground(){const g=$('#backgroundLayer');g.innerHTML='';const p=currentPage(),isPdf=p?.source?.type==='pdf';$('#pageStage').classList.toggle('pdfPage',!!isPdf);$('.paper').setAttribute('fill',isPdf?'transparent':'white');if(p?.bg){const im=document.createElementNS(NS,'image'),rot=((Number(p.rotation)||0)%360+360)%360;im.setAttribute('href',p.bg.data);im.setAttribute('x',0);im.setAttribute('y',0);im.setAttribute('preserveAspectRatio','xMidYMid meet');if(rot===90){im.setAttribute('width',p.h);im.setAttribute('height',p.w);im.setAttribute('transform',`translate(${p.w} 0) rotate(90)`)}else if(rot===180){im.setAttribute('width',p.w);im.setAttribute('height',p.h);im.setAttribute('transform',`translate(${p.w} ${p.h}) rotate(180)`)}else if(rot===270){im.setAttribute('width',p.h);im.setAttribute('height',p.w);im.setAttribute('transform',`translate(0 ${p.h}) rotate(270)`)}else{im.setAttribute('width',p.w);im.setAttribute('height',p.h)}g.appendChild(im)}}
function clearPdfUnderlay(){const c=$('#pdfCanvas'),t=$('#pdfTextLayer');c.classList.add('hidden');t.classList.add('hidden');t.innerHTML='';c.width=c.height=1}
async function renderPdfUnderlay(){const p=currentPage(),token=++state.pdfRenderToken,c=$('#pdfCanvas'),tl=$('#pdfTextLayer');if(!p||p.source?.type!=='pdf'||!state.pdfDoc){clearPdfUnderlay();return}try{const page=await state.pdfDoc.getPage(p.source.pageNumber),cssScale=96/72*state.zoom,dpr=Math.min(2,window.devicePixelRatio||1),rot=p.rotation||0,renderVp=page.getViewport({scale:cssScale*dpr,rotation:rot}),cssVp=page.getViewport({scale:cssScale,rotation:rot});if(token!==state.pdfRenderToken)return;c.width=Math.max(1,Math.round(renderVp.width));c.height=Math.max(1,Math.round(renderVp.height));c.style.width=cssVp.width+'px';c.style.height=cssVp.height+'px';c.classList.remove('hidden');await page.render({canvasContext:c.getContext('2d',{alpha:false}),viewport:renderVp}).promise;if(token!==state.pdfRenderToken)return;await renderPdfTextLayer(page,cssVp,token)}catch(err){console.error('PDF render failed',err);toast('PDF page render failed: '+(err.message||err))}}
async function renderPdfTextLayer(page,viewport,token){const tl=$('#pdfTextLayer');tl.innerHTML='';tl.style.width=viewport.width+'px';tl.style.height=viewport.height+'px';try{const text=await page.getTextContent(),styles=text.styles||{},lib=await ensurePdfJs();if(token!==state.pdfRenderToken)return;for(const item of text.items||[]){if(!item.str)continue;const tx=lib.Util.transform(viewport.transform,item.transform),angle=Math.atan2(tx[1],tx[0]),height=Math.hypot(tx[2],tx[3])||Math.abs(item.height*viewport.scale)||10,span=document.createElement('span');span.textContent=item.str;span.style.left=tx[4]+'px';span.style.top=(tx[5]-height)+'px';span.style.fontSize=height+'px';span.style.fontFamily=styles[item.fontName]?.fontFamily||'sans-serif';span.style.transformOrigin='0 0';span.style.transform=`rotate(${angle}rad)`;span.style.position='absolute';span.style.whiteSpace='pre';tl.appendChild(span)}tl.classList.remove('hidden');tl.classList.toggle('active',state.tool==='textselect')}catch(err){console.warn('Text layer unavailable',err);tl.classList.add('hidden')}}
function clearDynamicPatterns(){$$('#svgDefs [data-dyn="1"]').forEach(n=>n.remove())}
function ensureHatchPattern(m){if(!m.hatch||m.hatch==='none')return null;const defs=$('#svgDefs'),id='pat_'+m.id.replace(/[^a-z0-9_]/gi,'_');if($('#'+id))return id;const p=document.createElementNS(NS,'pattern');p.id=id;p.dataset.dyn='1';p.setAttribute('patternUnits','userSpaceOnUse');const s=Math.max(3,Number(m.hatchSpacing)||10);p.setAttribute('width',s);p.setAttribute('height',s);const bg=document.createElementNS(NS,'rect');bg.setAttribute('width',s);bg.setAttribute('height',s);bg.setAttribute('fill',m.fill||'#fff');bg.setAttribute('fill-opacity',m.fillOpacity??0);p.appendChild(bg);const c=m.hatchColor||m.stroke||'#000',w=Math.max(.5,Math.min(4,(m.width||1)*.65));const path=(d,sw=w)=>{const x=document.createElementNS(NS,'path');x.setAttribute('d',d);x.setAttribute('stroke',c);x.setAttribute('stroke-width',sw);x.setAttribute('fill','none');x.setAttribute('opacity',m.opacity??1);p.appendChild(x)};const circ=(cx,cy,r,fill=c)=>{const x=document.createElementNS(NS,'circle');x.setAttribute('cx',cx);x.setAttribute('cy',cy);x.setAttribute('r',r);x.setAttribute('fill',fill);p.appendChild(x)};
 switch(m.hatch){
  // ANSI-style drafting hatches. These are geometric plan-review patterns,
  // not material-certification symbols; line/color/spacing remain editable.
  case'ansi31':p.setAttribute('patternTransform','rotate(45)');path(`M0 0V${s}`);break;
  case'ansi32':p.setAttribute('patternTransform','rotate(45)');path(`M0 0V${s}`,w);path(`M${s*.35} 0V${s}`,Math.max(.45,w*.55));break;
  case'ansi33':p.setAttribute('patternTransform','rotate(45)');path(`M0 0V${s}`,w);path(`M${s*.5} 0V${s}`,w);break;
  case'ansi34':p.setAttribute('patternTransform','rotate(45)');path(`M0 0V${s}`,w);p.setAttribute('width',s*1.5);break;
  case'ansi35':path(`M0 ${s}L${s} 0`,w);path(`M0 ${s*.5}L${s*.5} 0`,Math.max(.45,w*.6));break;
  case'ansi36':path(`M0 ${s}L${s} 0M0 0L${s} ${s}`,Math.max(.5,w*.8));break;
  case'ansi37':path(`M0 ${s*.25}H${s}M0 ${s*.75}H${s}`,Math.max(.5,w*.8));path(`M${s*.25} 0V${s*.5}M${s*.75} ${s*.5}V${s}`,Math.max(.45,w*.55));break;
  case'ansi38':circ(s*.25,s*.25,Math.max(.7,s*.075));circ(s*.75,s*.75,Math.max(.7,s*.075));path(`M0 ${s}L${s} 0`,Math.max(.45,w*.5));break;
  case'diag45':p.setAttribute('patternTransform','rotate(45)');path(`M0 0V${s}`);break;case'diag135':p.setAttribute('patternTransform','rotate(135)');path(`M0 0V${s}`);break;
  case'cross45':path(`M0 ${s}L${s} 0M0 0L${s} ${s}`);break;case'horizontal':path(`M0 ${s/2}H${s}`);break;case'vertical':path(`M${s/2} 0V${s}`);break;case'grid':path(`M0 ${s/2}H${s}M${s/2} 0V${s}`);break;case'dots':circ(s/2,s/2,Math.max(1,s*.1));break;
  case'earth':path(`M0 ${s*.65} Q${s*.25} ${s*.35} ${s*.5} ${s*.65}T${s} ${s*.65}`,.8);circ(s*.18,s*.22,.7);circ(s*.72,s*.22,.7);break;
  case'sand':circ(s*.2,s*.25,.65);circ(s*.7,s*.2,.8);circ(s*.5,s*.7,.6);circ(s*.88,s*.72,.5);break;
  case'gravel':path(`M1 ${s*.4}L${s*.28} 1L${s*.5} ${s*.38}L${s*.8} ${s*.12}L${s-1} ${s*.55}L${s*.6} ${s-1}L${s*.3} ${s*.65}Z`,.7);break;
  case'concrete':path(`M1 1L${s*.3} ${s*.25}L${s*.12} ${s*.55}M${s*.65} ${s*.12}L${s*.9} ${s*.35}L${s*.7} ${s*.65}M${s*.2} ${s*.85}L${s*.45} ${s*.62}`,.65);circ(s*.52,s*.35,.6);break;
  case'riprap':path(`M1 ${s*.3}L${s*.35} 1L${s*.65} ${s*.28}L${s-1} ${s*.12}L${s*.82} ${s*.7}L${s*.48} ${s-1}L${s*.18} ${s*.72}Z`,.8);break;
  case'asphalt':for(let i=0;i<7;i++)circ((i*3.7%s),((i*5.1+2)%s),.55);break;
  case'demo':p.setAttribute('patternTransform','rotate(45)');path(`M0 0V${s}`,1.4);path(`M${s/2} 0V${s}`,.5);break;case'proposed':p.setAttribute('patternTransform','rotate(45)');path(`M0 0V${s}`,.9);break;case'existing':path(`M0 ${s/2}H${s}`,.7);break;
 }
 defs.appendChild(p);return id}
function commonAttrs(el,m){el.dataset.id=m.id;el.classList.add('markup');el.setAttribute('stroke',m.stroke||'none');el.setAttribute('stroke-width',m.width??2);el.setAttribute('opacity',m.opacity??1);if(m.dash)el.setAttribute('stroke-dasharray',m.dash);const pat=ensureHatchPattern(m);let fill=pat?`url(#${pat})`:(m.fill||'none');el.setAttribute('fill',fill);if(!pat&&fill!=='none')el.setAttribute('fill-opacity',m.fillOpacity??0);if(m.rotation){const b=bounds(m);if(b)el.setAttribute('transform',`rotate(${m.rotation} ${b.x+b.w/2} ${b.y+b.h/2})`)}if(state.selected===m.id)el.classList.add('selected');el.addEventListener('pointerdown',e=>objectPointerDown(e,m));el.addEventListener('contextmenu',e=>openContext(e,m.id));if(TEXT_TYPES.includes(m.type))el.addEventListener('dblclick',e=>{e.stopPropagation();editText(m)});return el}
function svgEl(tag,attrs={}){const e=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));return e}
function wrapText(text,w,fontSize){const max=Math.max(3,Math.floor(Math.max(20,w)/(Math.max(6,fontSize)*.57))),words=String(text||'').split(/\s+/),lines=[];let line='';for(const word of words){const test=line?line+' '+word:word;if(test.length>max&&line){lines.push(line);line=word}else line=test}if(line||!lines.length)lines.push(line);return lines}
function renderTextBlock(g,m){if(state.editing===m.id)return;const fs=m.fontSize||14,lines=wrapText(m.text||'',m.w||180,fs),tx=svgEl('text',{'font-size':fs,'font-family':m.font||'Arial','font-weight':m.bold?'700':'400','font-style':m.italic?'italic':'normal',fill:m.textColor||m.stroke||'#111'});let anchor='start',x=m.x+4;if(m.textAlign==='center'){anchor='middle';x=m.x+m.w/2}else if(m.textAlign==='right'){anchor='end';x=m.x+m.w-4}tx.setAttribute('text-anchor',anchor);lines.slice(0,Math.max(1,Math.floor((m.h||40)/(fs*1.18)))).forEach((ln,i)=>{const t=svgEl('tspan',{x,dy:i===0?fs+3:fs*1.18});if(i===0)t.setAttribute('y',m.y);t.textContent=ln;tx.appendChild(t)});tx.dataset.id=m.id;tx.classList.add('markup');tx.addEventListener('pointerdown',e=>objectPointerDown(e,m));tx.addEventListener('contextmenu',e=>openContext(e,m.id));tx.addEventListener('dblclick',e=>{e.stopPropagation();editText(m)});g.appendChild(tx)}
function renderTrafficSign(g,m){const group=svgEl('g');commonAttrs(group,m);const x=m.x,y=m.y,w=m.w,h=m.h,bg=m.signBg||'white',shape=m.signShape||'rectangle';if(m.assetData){const im=svgEl('image',{x,y,width:w,height:h,href:m.assetData,preserveAspectRatio:'xMidYMid meet'});group.appendChild(im);if(m.showCode!==false){const lab=svgEl('text',{x:x+w/2,y:y+h+9,'text-anchor':'middle','font-size':7,fill:'#222'});lab.textContent=m.signCode||'';group.appendChild(lab)}g.appendChild(group);return}let face;const fill=bg==='orange'?'#f5a623':bg==='yellow'?'#ffd32a':bg==='green'?'#168348':bg==='blue'?'#1768ad':bg.includes('red')?'#c9222c':'#fff',stroke=bg.includes('red')?'#fff':'#111';if(shape==='diamond'){face=svgEl('rect',{x:x+w*.15,y:y+h*.15,width:w*.7,height:h*.7,fill,stroke,'stroke-width':2,transform:`rotate(45 ${x+w/2} ${y+h/2})`})}else if(shape==='octagon'){const pts=[[.29,0],[.71,0],[1,.29],[1,.71],[.71,1],[.29,1],[0,.71],[0,.29]].map(([a,b])=>`${x+a*w},${y+b*h}`).join(' ');face=svgEl('polygon',{points:pts,fill:'#c9222c',stroke:'#fff','stroke-width':3})}else if(shape==='triangle'){const pts=`${x+w/2},${y+h} ${x},${y+h*.08} ${x+w},${y+h*.08}`;face=svgEl('polygon',{points:pts,fill:'#fff',stroke:'#c9222c','stroke-width':4})}else{face=svgEl('rect',{x,y,width:w,height:h,rx:2,fill,stroke,'stroke-width':2})}group.appendChild(face);const dark=(bg==='green'||bg==='blue'||shape==='octagon')?'#fff':'#111',fs=Math.max(6,Math.min(13,Math.min(w,h)*.15)),lines=wrapText(m.signName||m.text||m.subject,w*.85,fs).slice(0,3),tx=svgEl('text',{x:x+w/2,y:y+h/2-(lines.length-1)*fs*.55,'text-anchor':'middle','font-size':fs,'font-weight':'800',fill:dark});lines.forEach((ln,i)=>{const t=svgEl('tspan',{x:x+w/2,dy:i?fs*1.05:0});t.textContent=ln.toUpperCase();tx.appendChild(t)});group.appendChild(tx);if(m.showCode!==false){const lab=svgEl('text',{x:x+w/2,y:y+h+9,'text-anchor':'middle','font-size':7,fill:'#222'});lab.textContent=m.signCode||'';group.appendChild(lab)}g.appendChild(group)}
function renderDevice(g,m){const group=svgEl('g');commonAttrs(group,m);const x=m.x,y=m.y,w=m.w,h=m.h,k=m.deviceKind||'cone';if(k==='cone'){group.appendChild(svgEl('path',{d:`M${x+w/2} ${y} L${x+w} ${y+h} L${x} ${y+h} Z`,fill:'#f58220',stroke:'#222','stroke-width':1}));group.appendChild(svgEl('rect',{x:x-2,y:y+h-3,width:w+4,height:4,fill:'#333'}))}else if(k==='drum'){group.appendChild(svgEl('rect',{x:x+w*.15,y:y,width:w*.7,height:h,rx:w*.15,fill:'#f58220',stroke:'#222','stroke-width':1}));group.appendChild(svgEl('rect',{x:x+w*.15,y:y+h*.38,width:w*.7,height:h*.18,fill:'#fff'}))}else if(k==='verticalPanel'){group.appendChild(svgEl('rect',{x:x+w*.3,y:y,width:w*.4,height:h,fill:'#fff',stroke:'#222'}));for(let i=0;i<3;i++)group.appendChild(svgEl('path',{d:`M${x+w*.3} ${y+i*h/3}L${x+w*.7} ${y+(i+1)*h/3}`,stroke:'#f58220','stroke-width':4}))}else if(k==='barricade'){[.2,.48,.76].forEach(q=>{group.appendChild(svgEl('rect',{x,y:y+h*q,width:w,height:h*.13,fill:'#fff',stroke:'#333'}));group.appendChild(svgEl('path',{d:`M${x} ${y+h*q}L${x+w} ${y+h*(q+.13)}`,stroke:'#f58220','stroke-width':5}))});group.appendChild(svgEl('line',{x1:x+w*.15,y1:y+h*.2,x2:x+w*.1,y2:y+h,stroke:'#333','stroke-width':3}));group.appendChild(svgEl('line',{x1:x+w*.85,y1:y+h*.2,x2:x+w*.9,y2:y+h,stroke:'#333','stroke-width':3}))}else if(k==='barrier'){group.appendChild(svgEl('path',{d:`M${x+w*.1} ${y}H${x+w*.9}L${x+w} ${y+h}H${x}Z`,fill:'#ddd',stroke:'#555','stroke-width':1}))}else{group.appendChild(svgEl('rect',{x,y,width:w,height:h,rx:2,fill:'#fff',stroke:'#222','stroke-width':1.5}));const t=svgEl('text',{x:x+w/2,y:y+h/2+3,'text-anchor':'middle','font-size':Math.max(6,h*.2),'font-weight':'700'});t.textContent=m.deviceCode||k.toUpperCase();group.appendChild(t)}g.appendChild(group)}
function renderMarkups(){clearDynamicPatterns();const g=$('#markupLayer');g.innerHTML='';for(const m of currentPage().markups){if(!isMarkupVisible(m))continue;let el;if(['rect','square','highlight','hatch'].includes(m.type)){el=svgEl('rect',{x:m.x,y:m.y,width:m.w,height:m.h});commonAttrs(el,m);g.appendChild(el)}else if(['ellipse','circle'].includes(m.type)){el=svgEl('ellipse',{cx:m.x+m.w/2,cy:m.y+m.h/2,rx:Math.abs(m.w/2),ry:Math.abs(m.h/2)});commonAttrs(el,m);g.appendChild(el)}else if(['textbox','note','text'].includes(m.type)){el=svgEl('rect',{x:m.x,y:m.y,width:m.w,height:m.h,rx:m.type==='note'?3:0});commonAttrs(el,m);if(m.type==='text'&&m.width===0)el.setAttribute('stroke','none');g.appendChild(el);renderTextBlock(g,m)}else if(m.type==='stamp'){el=svgEl('g');commonAttrs(el,m);const r=svgEl('rect',{x:m.x,y:m.y,width:m.w,height:m.h,rx:2,fill:m.fill||'#fff','fill-opacity':m.fillOpacity??1,stroke:m.stroke||'none','stroke-width':m.width??0});el.appendChild(r);if(m.assetData){el.appendChild(svgEl('image',{x:m.x+2,y:m.y+2,width:Math.max(1,m.w-4),height:Math.max(1,m.h-4),href:m.assetData,preserveAspectRatio:'xMidYMid meet'}))}else{const tx=svgEl('text',{x:m.x+m.w/2,y:m.y+m.h/2+4,'text-anchor':'middle','font-size':Math.max(7,Math.min(14,m.h*.26)),'font-weight':'800',fill:m.textColor||m.stroke});tx.textContent=m.text;el.appendChild(tx)}g.appendChild(el)}else if(m.type==='trafficSign'){renderTrafficSign(g,m)}else if(m.type==='device'){renderDevice(g,m)}else if(LINE_TYPES.includes(m.type)){el=svgEl('line',{x1:m.x,y1:m.y,x2:m.x2,y2:m.y2});commonAttrs(el,m);el.setAttribute('fill','none');if(['arrow','callout'].includes(m.type))el.setAttribute('marker-end','url(#arrowHead)');if(m.startArrow)el.setAttribute('marker-start','url(#arrowStart)');g.appendChild(el);if(m.type==='measure'){const tx=svgEl('text',{x:(m.x+m.x2)/2,y:(m.y+m.y2)/2-5,'font-size':10,fill:m.stroke});tx.textContent=distanceText(m);g.appendChild(tx)}if(m.type==='deviceRun')renderDeviceRun(g,m)}else if(m.type==='freehand'){el=svgEl('path',{d:m.d});commonAttrs(el,m);el.setAttribute('fill','none');g.appendChild(el)}else if(POLY_TYPES.includes(m.type)){if(m.points?.length){const points=m.points.map(p=>p.join(',')).join(' ');if(m.type==='cloudFree'){el=svgEl('path',{d:cloudPolygonPath(m.points)});commonAttrs(el,m);g.appendChild(el)}else if(m.type==='polyline'){el=svgEl('polyline',{points,fill:'none'});commonAttrs(el,m);el.setAttribute('fill','none');g.appendChild(el)}else{el=svgEl('polygon',{points});commonAttrs(el,m);g.appendChild(el)}}}else if(m.type==='cloud'){el=svgEl('path',{d:cloudRectPath(m.x,m.y,m.w,m.h)});commonAttrs(el,m);g.appendChild(el)}
 }renderSelection()}
function distanceText(m){return Math.hypot(m.x2-m.x,m.y2-m.y).toFixed(1)+' pt'}
function renderDeviceRun(g,m){const len=Math.hypot(m.x2-m.x,m.y2-m.y),step=Math.max(12,Number(m.deviceSpacing)||30),n=Math.max(1,Math.floor(len/step));for(let i=0;i<=n;i++){const t=i/n,cx=m.x+(m.x2-m.x)*t,cy=m.y+(m.y2-m.y)*t,d={id:m.id+'_d'+i,type:'device',x:cx-6,y:cy-8,w:12,h:16,deviceKind:m.deviceKind||'cone',deviceCode:m.deviceCode||'CONE',stroke:'#222',width:1,fill:'#f58220',fillOpacity:1,opacity:1};renderDevice(g,d)}}
function bounds(m){if(LINE_TYPES.includes(m.type))return{x:Math.min(m.x,m.x2),y:Math.min(m.y,m.y2),w:Math.abs(m.x2-m.x),h:Math.abs(m.y2-m.y)};if(m.type==='freehand')return m.bounds||null;if(POLY_TYPES.includes(m.type)){if(!m.points?.length)return null;const xs=m.points.map(p=>p[0]),ys=m.points.map(p=>p[1]);return{x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...xs)-Math.min(...xs),h:Math.max(...ys)-Math.min(...ys)}}return{x:m.x,y:m.y,w:m.w||1,h:m.h||1}}
function renderSelection(){const ig=$('#interactionLayer');ig.innerHTML='';const m=selectedMarkup();if(!m)return;const b=bounds(m);if(!b)return;const r=svgEl('rect',{x:b.x-3,y:b.y-3,width:b.w+6,height:b.h+6,class:'selectionBox'});ig.appendChild(r);if(m.locked)return;if(LINE_TYPES.includes(m.type)){[['start',m.x,m.y],['end',m.x2,m.y2]].forEach(([d,x,y])=>{const h=svgEl('circle',{cx:x,cy:y,r:4,class:'endpoint'});h.dataset.dir=d;h.addEventListener('pointerdown',e=>resizePointerDown(e,m,d));ig.appendChild(h)});return}const pts={nw:[b.x,b.y],n:[b.x+b.w/2,b.y],ne:[b.x+b.w,b.y],e:[b.x+b.w,b.y+b.h/2],se:[b.x+b.w,b.y+b.h],s:[b.x+b.w/2,b.y+b.h],sw:[b.x,b.y+b.h],w:[b.x,b.y+b.h/2]};Object.entries(pts).forEach(([d,[x,y]])=>{const h=svgEl('rect',{x:x-3,y:y-3,width:6,height:6,class:'handle'});h.dataset.dir=d;h.addEventListener('pointerdown',e=>resizePointerDown(e,m,d));ig.appendChild(h)})}
function svgPoint(e){const svg=$('#pageSvg'),pt=svg.createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;return pt.matrixTransform(svg.getScreenCTM().inverse())}
function translateMarkup(m,dx,dy,orig){if(LINE_TYPES.includes(m.type)){m.x=orig.x+dx;m.y=orig.y+dy;m.x2=orig.x2+dx;m.y2=orig.y2+dy}else if(POLY_TYPES.includes(m.type)){m.points=orig.points.map(([x,y])=>[x+dx,y+dy])}else if(m.type==='freehand'){m.points=orig.points.map(([x,y])=>[x+dx,y+dy]);rebuildFreehand(m)}else{m.x=orig.x+dx;m.y=orig.y+dy}}
function objectPointerDown(e,m){if(state.tool!=='select'||isMarkupLocked(m))return;checkpoint();e.stopPropagation();state.selected=m.id;state.propertyMode='object';renderSelection();updateProperties();const start=svgPoint(e),orig=JSON.parse(JSON.stringify(m));const move=ev=>{const q=svgPoint(ev);translateMarkup(m,q.x-start.x,q.y-start.y,orig);renderMarkups();if(state.editing===m.id)positionInlineEditor()};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);m.modified=new Date().toISOString();renderTable()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}
function resizePointerDown(e,m,dir){checkpoint();e.stopPropagation();e.preventDefault();const start=svgPoint(e),orig=JSON.parse(JSON.stringify(m)),ob=bounds(orig);const move=ev=>{const q=svgPoint(ev),dx=q.x-start.x,dy=q.y-start.y;if(LINE_TYPES.includes(m.type)){if(dir==='start'){m.x=orig.x+dx;m.y=orig.y+dy}else{m.x2=orig.x2+dx;m.y2=orig.y2+dy}}else{let nx=ob.x,ny=ob.y,nw=ob.w,nh=ob.h;if(dir.includes('e'))nw=Math.max(4,ob.w+dx);if(dir.includes('s'))nh=Math.max(4,ob.h+dy);if(dir.includes('w')){nx=Math.min(ob.x+ob.w-4,ob.x+dx);nw=Math.max(4,ob.w-dx)}if(dir.includes('n')){ny=Math.min(ob.y+ob.h-4,ob.y+dy);nh=Math.max(4,ob.h-dy)}applyBounds(m,orig,ob,{x:nx,y:ny,w:nw,h:nh})}renderMarkups();if(state.editing===m.id)positionInlineEditor()};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);m.modified=new Date().toISOString();renderTable()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}
function applyBounds(m,orig,ob,nb){if(POLY_TYPES.includes(m.type)||m.type==='freehand'){const sx=ob.w?nb.w/ob.w:1,sy=ob.h?nb.h/ob.h:1;m.points=orig.points.map(([x,y])=>[nb.x+(x-ob.x)*sx,nb.y+(y-ob.y)*sy]);if(m.type==='freehand')rebuildFreehand(m)}else{m.x=nb.x;m.y=nb.y;m.w=nb.w;m.h=nb.h}}
function rebuildFreehand(m){m.d=m.points.map((p,i)=>(i?'L':'M')+p[0]+' '+p[1]).join(' ');const xs=m.points.map(p=>p[0]),ys=m.points.map(p=>p[1]);m.bounds={x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...xs)-Math.min(...xs),h:Math.max(...ys)-Math.min(...ys)}}
function cloudRectPath(x,y,w,h){return cloudPolygonPath([[x,y],[x+w,y],[x+w,y+h],[x,y+h]])}
function cloudPolygonPath(points){if(!points?.length)return'';const pts=[...points,points[0]],r=10;let d=`M${points[0][0]} ${points[0][1]}`;for(let s=0;s<points.length;s++){const [x1,y1]=pts[s],[x2,y2]=pts[s+1],dx=x2-x1,dy=y2-y1,len=Math.max(1,Math.hypot(dx,dy)),n=Math.max(1,Math.round(len/r));for(let i=1;i<=n;i++){const t0=(i-1)/n,t1=i/n,mx=x1+dx*(t0+t1)/2,my=y1+dy*(t0+t1)/2,px=-dy/len,py=dx/len,bulge=Math.min(5,len/n*.35),ex=x1+dx*t1,ey=y1+dy*t1;d+=` Q${mx+px*bulge} ${my+py*bulge} ${ex} ${ey}`}}return d+' Z'}
function startZoomRect(e,start){const ig=$('#interactionLayer'),r=svgEl('rect',{class:'zoomRect'});ig.appendChild(r);const move=ev=>{const q=svgPoint(ev);r.setAttribute('x',Math.min(start.x,q.x));r.setAttribute('y',Math.min(start.y,q.y));r.setAttribute('width',Math.abs(q.x-start.x));r.setAttribute('height',Math.abs(q.y-start.y))};const up=ev=>{const q=svgPoint(ev),w=Math.abs(q.x-start.x),h=Math.abs(q.y-start.y);window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);if(w>5&&h>5){const a=$('#canvasScroller'),factor=Math.min((a.clientWidth-40)/(w*96/72),(a.clientHeight-40)/(h*96/72));setZoom(factor);requestAnimationFrame(()=>{const cx=(Math.min(start.x,q.x)+w/2)*96/72*state.zoom,cy=(Math.min(start.y,q.y)+h/2)*96/72*state.zoom;a.scrollLeft=Math.max(0,cx-a.clientWidth/2);a.scrollTop=Math.max(0,cy-a.clientHeight/2)})}renderMarkups();setTool('hand')};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}
function baseMarkup(type,p){return{id:uid(),type,x:p.x,y:p.y,x2:p.x,y2:p.y,w:1,h:1,d:'',layer:type==='measure'?'measurements':state.activeLayer,subject:toolLabel(type),comment:'',status:'Open',created:new Date().toISOString(),modified:new Date().toISOString(),...style()}}
$('#pageSvg').addEventListener('pointerdown',e=>{if(e.button!==0)return;const p=svgPoint(e);if(state.tool==='select'){if(e.target.closest?.('.markup'))return;state.selected=null;state.propertyMode='object';renderMarkups();updateProperties();return}if(['hand','textselect'].includes(state.tool)||POLY_TYPES.includes(state.tool))return;if(state.tool==='zoom'){startZoomRect(e,p);return}if(state.tool==='text'){checkpoint();const m={...baseMarkup('text',p),type:'text',w:170,h:28,width:0,stroke:'#111',fill:'#fff',fillOpacity:0,text:'',fontSize:state.preset.fontSize||14,textColor:state.preset.textColor||'#111'};addMarkup(m,false);editText(m);return}checkpoint();const m=baseMarkup(state.tool,p);if(state.tool==='highlight'){m.fill='#ffe000';m.fillOpacity=.4;m.stroke='none';m.width=0}if(state.tool==='hatch'){m.hatch=state.preset.hatch==='none'?'diag45':state.preset.hatch;m.fillOpacity=state.preset.fillOpacity??0}if(state.tool==='textbox'){m.text='';m.fill='#fff';m.fillOpacity=0;m.stroke='#111';m.width=1;m.fontSize=state.preset.fontSize||14;m.textColor=state.preset.textColor||'#111'}if(state.tool==='note'){m.text='';m.fill='#fff6b8';m.fillOpacity=.85;m.stroke='#555';m.width=1;m.fontSize=state.preset.fontSize||14;m.textColor='#111'}if(state.tool==='freehand'){m.points=[[p.x,p.y]];m.d=`M${p.x} ${p.y}`}currentPage().markups.push(m);state.drawing=m;const move=ev=>drawingMove(ev,m,p);const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);finishDrawing(m);state.drawing=null};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)});
function drawingMove(ev,m,start){const q=svgPoint(ev);if(LINE_TYPES.includes(m.type)){m.x2=q.x;m.y2=q.y}else if(m.type==='freehand'){m.points.push([q.x,q.y]);rebuildFreehand(m)}else{let w=Math.abs(q.x-start.x),h=Math.abs(q.y-start.y),x=Math.min(start.x,q.x),y=Math.min(start.y,q.y);if(['square','circle'].includes(m.type)){const z=Math.max(w,h);w=h=z;x=q.x<start.x?start.x-z:start.x;y=q.y<start.y?start.y-z:start.y}m.x=x;m.y=y;m.w=w;m.h=h}renderMarkups()}
function finishDrawing(m){const b=bounds(m);if(b&&b.w<2&&b.h<2&&!LINE_TYPES.includes(m.type)&&m.type!=='freehand'){currentPage().markups=currentPage().markups.filter(x=>x!==m);render();return}state.selected=m.id;state.propertyMode='object';render();setTool('select');if(['textbox','note'].includes(m.type))editText(m)}
$('#pageSvg').addEventListener('click',e=>{if(!POLY_TYPES.includes(state.tool)||e.detail>1)return;const p=svgPoint(e);if(!state.polyDraft){checkpoint();const m=baseMarkup(state.tool,p);m.points=[[p.x,p.y]];if(state.tool==='hatchFree')m.hatch=state.preset.hatch==='none'?'diag45':state.preset.hatch;if(state.tool==='cloudFree'){m.fill='#fff';m.fillOpacity=0}currentPage().markups.push(m);state.polyDraft=m}else state.polyDraft.points.push([p.x,p.y]);renderMarkups()});
$('#pageSvg').addEventListener('dblclick',e=>{if(!POLY_TYPES.includes(state.tool))return;e.preventDefault();finishPolyDraft(true)});
function finishPolyDraft(select=true){const m=state.polyDraft;if(!m)return;if(m.points.length>1){const a=m.points.at(-1),b=m.points.at(-2);if(Math.hypot(a[0]-b[0],a[1]-b[1])<5)m.points.pop()}const need=m.type==='polyline'?2:3;if(m.points.length<need)currentPage().markups=currentPage().markups.filter(x=>x!==m);else if(select){state.selected=m.id;m.modified=new Date().toISOString()}state.polyDraft=null;render();if(select)setTool('select')}
function addMarkup(obj,select=true){checkpoint();obj.id=obj.id||uid();obj.layer=obj.layer||state.activeLayer||'default';obj.created=obj.created||new Date().toISOString();obj.modified=new Date().toISOString();obj.status=obj.status||'Open';currentPage().markups.push(obj);if(select){state.selected=obj.id;state.propertyMode='object'}render();if(select)setTool('select')}
function editText(m){if(!m||!TEXT_TYPES.includes(m.type)||isMarkupLocked(m))return;if(state.editing!==m.id)checkpoint();state.selected=m.id;state.editing=m.id;state.tool='select';renderMarkups();const ed=$('#inlineEditor');ed.value=m.text||'';ed.classList.remove('hidden');positionInlineEditor();ed.focus();ed.setSelectionRange(ed.value.length,ed.value.length)}
function positionInlineEditor(){const m=selectedMarkup();if(!m||state.editing!==m.id)return;const ed=$('#inlineEditor'),s=96/72*state.zoom;ed.style.left=m.x*s+'px';ed.style.top=m.y*s+'px';ed.style.width=Math.max(30,m.w*s)+'px';ed.style.height=Math.max(20,m.h*s)+'px';ed.style.fontFamily=m.font||'Arial';ed.style.fontSize=(m.fontSize||14)*s+'px';ed.style.fontWeight=m.bold?'700':'400';ed.style.fontStyle=m.italic?'italic':'normal';ed.style.color=m.textColor||'#111';ed.style.textAlign=m.textAlign||'left';ed.style.background=colorWithAlpha(m.fill||'#fff',m.fillOpacity??0)}
function colorWithAlpha(hex,a){if(!/^#[0-9a-f]{6}$/i.test(hex))return'rgba(255,255,255,.8)';const n=parseInt(hex.slice(1),16);return`rgba(${n>>16},${n>>8&255},${n&255},${Math.max(.08,a)})`}
$('#inlineEditor').addEventListener('input',e=>{const m=selectedMarkup();if(m&&state.editing===m.id){m.text=e.target.value;m.modified=new Date().toISOString()}});$('#inlineEditor').addEventListener('blur',finishInlineEdit);$('#inlineEditor').addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();finishInlineEdit()}e.stopPropagation()});function finishInlineEdit(){const m=selectedMarkup(),ed=$('#inlineEditor');if(m&&state.editing===m.id)m.text=ed.value;state.editing=null;ed.classList.add('hidden');renderMarkups();renderTable()}
function addStamp(text,assetData=null,assetAspect=null){const b=viewportCenterOnPage();let w=190,h=44;if(assetData){const a=Math.max(.2,Math.min(5,Number(assetAspect)||2));w=150;h=Math.max(45,Math.min(120,w/a))}addMarkup({type:'stamp',x:b.x-w/2,y:b.y-h/2,w,h,text,assetData,assetAspect,subject:text,comment:'',status:'Open',stroke:assetData?'#666666':(text.startsWith('TTC')?'#d66b12':(text.includes('SIGNAL')||text.startsWith('SIGN ')?'#1b5fa6':'#b5252b')),width:assetData?0:2,fill:'#fff',fillOpacity:assetData?0:1,dash:'',hatch:'none',hatchColor:'#000',hatchSpacing:10,opacity:1,rotation:0})}
function svgAspectFromText(text){const vb=text.match(/viewBox\s*=\s*["']\s*[-+0-9.eE]+[ ,]+[-+0-9.eE]+[ ,]+([-+0-9.eE]+)[ ,]+([-+0-9.eE]+)\s*["']/i);if(vb){const w=Math.abs(Number(vb[1])),h=Math.abs(Number(vb[2]));if(w&&h)return w/h}const wm=text.match(/\bwidth\s*=\s*["']([0-9.]+)(?:px|pt)?["']/i),hm=text.match(/\bheight\s*=\s*["']([0-9.]+)(?:px|pt)?["']/i);if(wm&&hm&&Number(hm[1]))return Number(wm[1])/Number(hm[1]);return 1}
async function fetchSignAssetData(s){if(s.assetData)return{data:s.assetData,aspect:s.assetAspect||1};if(!s.svg)return{data:null,aspect:1};try{const url=new URL(MUTCD_ASSET_BASE+s.svg,location.href).href,text=await localText(url);return{data:'data:image/svg+xml;base64,'+btoa(unescape(encodeURIComponent(text))),aspect:svgAspectFromText(text)}}catch(err){console.warn('MUTCD asset unavailable',s.code,err);return{data:null,aspect:1}}}
async function addTrafficSign(s){const b=viewportCenterOnPage(),asset=await fetchSignAssetData(s),a=Math.max(.25,Math.min(4,asset.aspect||1)),max=78,w=a>=1?max:max*a,h=a>=1?max/a:max;addMarkup({type:'trafficSign',layer:'traffic',x:b.x-w/2,y:b.y-h/2,w,h,subject:`${s.code} ${s.name}`,comment:s.source||'FHWA MUTCD / Standard Highway Signs',status:'Open',signCode:s.code,signName:s.name,signShape:s.shape,signBg:s.background,assetData:asset.data,assetAspect:a,assetPath:s.svg||null,showCode:true,stroke:'#222',width:1,fill:'#fff',fillOpacity:1,dash:'',hatch:'none',opacity:1,rotation:0})}
function addTrafficDevice(d){const b=viewportCenterOnPage();if(['workZone','buffer'].includes(d.kind)){addMarkup({type:'hatch',layer:'traffic',x:b.x-90,y:b.y-45,w:180,h:90,subject:d.name,comment:'TxDOT temporary traffic control plan element',status:'Open',stroke:d.kind==='workZone'?'#d71920':'#1267b1',width:2,fill:'#fff',fillOpacity:.05,dash:d.kind==='buffer'?'8 5':'',hatch:d.kind==='workZone'?'diag45':'none',hatchColor:'#d71920',hatchSpacing:12,opacity:1});return}addMarkup({type:'device',layer:'traffic',x:b.x-18,y:b.y-25,w:36,h:50,deviceKind:d.kind,deviceCode:d.code,subject:d.name,comment:'TxDOT / TMUTCD traffic-control device',status:'Open',stroke:'#222',width:1,fill:'#fff',fillOpacity:1,dash:'',hatch:'none',opacity:1,rotation:0})}
function addStandardNote(s){const b=viewportCenterOnPage();addMarkup({type:'note',layer:'traffic',x:b.x-130,y:b.y-40,w:260,h:80,text:`${s.code}\n${s.name}${s.detail?'\n'+s.detail:''}`,subject:`TxDOT Standard ${s.code}`,comment:'Reference the current TxDOT Traffic Standards file before final use.',status:'Open',stroke:'#1267b1',width:1,fill:'#eaf5ff',fillOpacity:.95,hatch:'none',opacity:1,font:'Arial',fontSize:11,textColor:'#0b3f6d',textAlign:'left'})}
function viewportCenterOnPage(){const sc=$('#canvasScroller'),s=96/72*state.zoom;return{x:(sc.scrollLeft+sc.clientWidth/2)/s,y:(sc.scrollTop+sc.clientHeight/2)/s}}
function renderPages(){const box=$('#pageThumbs');box.innerHTML='';state.pages.forEach((p,i)=>{const b=document.createElement('button');b.className='pageThumb'+(i===state.pageIndex?' active':'');b.innerHTML=`<span class="thumbSheet" style="aspect-ratio:${p.w}/${p.h}"></span><span><strong>Page ${i+1}</strong><br>${esc(p.name)}</span>`;b.onclick=()=>{state.pageIndex=i;state.selected=null;render();fitPage()};box.appendChild(b)})}
function renderTable(){const rows=$('#markupRows'),filter=($('#markupFilter')?.value||'').toLowerCase();rows.innerHTML='';let n=0;state.pages.forEach((p,pi)=>p.markups.forEach(m=>{if(filter&&!(`${m.subject} ${m.comment} ${m.status}`.toLowerCase().includes(filter)))return;n++;const tr=document.createElement('tr');if(m.id===state.selected&&pi===state.pageIndex)tr.classList.add('selected');tr.innerHTML=`<td>${pi+1}</td><td>${esc(m.subject||toolLabel(m.type))}</td><td>${esc(m.status||'Open')}</td><td>${esc(m.comment||'')}</td><td>${new Date(m.modified||m.created).toLocaleString()}</td>`;tr.onclick=()=>{state.pageIndex=pi;state.selected=m.id;state.propertyMode='object';render()};rows.appendChild(tr)}));$('#markupCount').textContent=`${n} markup${n===1?'':'s'}`}
function propertyTarget(){if(state.propertyMode==='tool')return state.preset;return selectedMarkup()}
function isTextTarget(t){if(state.propertyMode==='tool')return TEXT_TYPES.includes(state.propertyTool);return t&&TEXT_TYPES.includes(t.type)}
function updateProperties(){const t=propertyTarget(),empty=!t;$('#propEmpty').classList.toggle('hidden',!empty);$('#propEditor').classList.toggle('hidden',empty);$('#propTitle').textContent=state.propertyMode==='tool'?`${toolLabel(state.propertyTool)} Defaults`:'Properties';$('#propHint').textContent=state.propertyMode==='tool'?'applies to newly drawn objects':(selectedMarkup()?.subject||'');if(!t)return;$('#propSubject').value=t.subject||'';$('#propStatus').value=t.status||'Open';$('#propComment').value=t.comment||'';$('#propStroke').value=validColor(t.stroke)?t.stroke:'#000000';$('#propWidth').value=t.width??2;$('#propFill').value=validColor(t.fill)?t.fill:'#ffffff';$('#propFillOpacity').value=t.fillOpacity??0;$('#propDash').value=t.dash||'';$('#propHatch').value=t.hatch||'none';$('#propHatchColor').value=validColor(t.hatchColor)?t.hatchColor:(validColor(t.stroke)?t.stroke:'#000000');$('#propHatchSpacing').value=t.hatchSpacing??10;$('#propOpacity').value=t.opacity??1;$('#propRotation').value=t.rotation||0;$('#propFont').value=t.font||'Arial';$('#propFontSize').value=t.fontSize||14;$('#propTextColor').value=validColor(t.textColor)?t.textColor:'#111111';$('#propTextAlign').value=t.textAlign||'left';$('#propBold').checked=!!t.bold;$('#propItalic').checked=!!t.italic;const layerSel=$('#propLayer');layerSel.innerHTML=state.layers.map(l=>`<option value="${esc(l.id)}">${esc(l.name)}</option>`).join('');layerSel.value=t.layer||state.activeLayer||'default';$('#textProps').classList.toggle('hidden',!isTextTarget(t));const objectOnly=state.propertyMode==='object';$('#propSubject').disabled=!objectOnly;$('#propStatus').disabled=!objectOnly;$('#propComment').disabled=!objectOnly;$('#duplicateObj').disabled=!objectOnly;$('#deleteObj').disabled=!objectOnly;$('#propLayer').disabled=!objectOnly}
function validColor(c){return /^#[0-9a-f]{6}$/i.test(c||'')}
function bindProp(id,key,evt='input',conv=v=>v){$(id).addEventListener(evt,e=>{const t=propertyTarget();if(!t)return;checkpoint();t[key]=conv(e.target.type==='checkbox'?e.target.checked:e.target.value);if(state.propertyMode==='object')t.modified=new Date().toISOString();renderMarkups();renderTable();if(state.editing)positionInlineEditor()})}
bindProp('#propSubject','subject');bindProp('#propStatus','status','change');bindProp('#propComment','comment');bindProp('#propStroke','stroke');bindProp('#propWidth','width','input',Number);bindProp('#propFill','fill');bindProp('#propFillOpacity','fillOpacity','input',Number);bindProp('#propDash','dash','change');bindProp('#propHatch','hatch','change');bindProp('#propHatchColor','hatchColor');bindProp('#propHatchSpacing','hatchSpacing','input',Number);bindProp('#propOpacity','opacity','input',Number);bindProp('#propRotation','rotation','input',Number);bindProp('#propFont','font','change');bindProp('#propFontSize','fontSize','input',Number);bindProp('#propTextColor','textColor');bindProp('#propTextAlign','textAlign','change');bindProp('#propBold','bold','change',Boolean);bindProp('#propItalic','italic','change',Boolean);bindProp('#propLayer','layer','change');
function duplicateSelected(){const m=selectedMarkup();if(!m)return;checkpoint();const c=JSON.parse(JSON.stringify(m)),orig=JSON.parse(JSON.stringify(m));c.id=uid();translateMarkup(c,12,12,orig);c.subject=(c.subject||'Markup')+' Copy';c.modified=new Date().toISOString();currentPage().markups.push(c);state.selected=c.id;render()}
function deleteSelected(){if(!state.selected)return;checkpoint();currentPage().markups=currentPage().markups.filter(x=>x.id!==state.selected);state.selected=null;finishInlineEdit();render()}
$('#duplicateObj').onclick=duplicateSelected;$('#deleteObj').onclick=deleteSelected;$('#savePreset').onclick=()=>{const m=selectedMarkup();if(m){copyAppearanceToPreset(m);toast('Appearance copied to current drawing defaults.')}else toast('Current tool defaults are already active.')};
function copyAppearanceToPreset(m){['stroke','width','fill','fillOpacity','dash','hatch','hatchColor','hatchSpacing','opacity','font','fontSize','textColor','textAlign','bold','italic'].forEach(k=>{if(m[k]!==undefined)state.preset[k]=m[k]})}
function openContext(e,id){e.preventDefault();e.stopPropagation();state.selected=id;state.propertyMode='object';renderMarkups();updateProperties();const cm=$('#contextMenu'),m=selectedMarkup();$$('#contextMenu .textOnly').forEach(x=>x.classList.toggle('hidden',!TEXT_TYPES.includes(m?.type)));cm.style.left=Math.min(e.clientX,window.innerWidth-180)+'px';cm.style.top=Math.min(e.clientY,window.innerHeight-230)+'px';cm.classList.remove('hidden')}
$('#contextMenu').addEventListener('click',e=>{const cmd=e.target.dataset.cmd;if(!cmd)return;const p=currentPage(),i=p.markups.findIndex(x=>x.id===state.selected),m=p.markups[i];if(cmd==='properties'){openPropertiesAt(null,'object')}else if(cmd==='editText'&&m)editText(m);else if(cmd==='duplicate')duplicateSelected();else if(cmd==='delete')deleteSelected();else if(cmd==='front'&&i>=0){p.markups.push(p.markups.splice(i,1)[0]);render()}else if(cmd==='back'&&i>=0){p.markups.unshift(p.markups.splice(i,1)[0]);render()}else if(cmd==='lock'&&m){m.locked=!m.locked;toast(m.locked?'Object locked':'Object unlocked');renderSelection()}else if(cmd==='preset'&&m){copyAppearanceToPreset(m);toast('Appearance copied to drawing defaults.')}$('#contextMenu').classList.add('hidden')});
function openPropertiesAt(point,mode='object',tool=null){state.propertyMode=mode;if(tool)state.propertyTool=tool;closePalettes('propertiesPalette');const p=$('#propertiesPalette');p.classList.remove('hidden');if(point&&window.innerWidth>620){p.style.left='auto';p.style.right=Math.max(6,window.innerWidth-point.x-20)+'px';p.style.top=Math.max(78,Math.min(point.y,window.innerHeight-p.offsetHeight-10))+'px'}else{p.style.left='';p.style.right='8px';p.style.top='80px'}updateProperties()}
function closePalettes(except){$$('.palette').forEach(p=>{if(p.id!==except)p.classList.add('hidden')})}
function togglePalette(id){const p=$('#'+id),opening=p.classList.contains('hidden');closePalettes(opening?id:null);p.classList.toggle('hidden',!opening);if(id==='propertiesPalette')updateProperties();if(id==='layersPalette')renderLayers();if(id==='trafficPalette')renderTrafficLibrary();if(id==='markupsPalette')renderTable()}
$$('[data-palette]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();togglePalette(b.dataset.palette)}));$$('[data-close]').forEach(b=>b.onclick=e=>{e.stopPropagation();b.closest('.palette').classList.add('hidden')});$('#btnProperties').onclick=e=>{e.stopPropagation();if(selectedMarkup())openPropertiesAt(null,'object');else openPropertiesAt(null,'tool',state.tool)};
$$('[data-tool]').forEach(b=>{b.addEventListener('click',()=>setTool(b.dataset.tool));b.addEventListener('contextmenu',e=>{e.preventDefault();e.stopPropagation();setTool(b.dataset.tool);openPropertiesAt({x:e.clientX,y:e.clientY},'tool',b.dataset.tool)})});
$$('[data-preset]').forEach(b=>b.onclick=()=>{if(b.dataset.preset==='reviewRed')Object.assign(state.preset,{stroke:'#d71920',width:2,fill:'#fff',fillOpacity:0,dash:'',hatch:'none',opacity:1});if(b.dataset.preset==='inspectionBlue')Object.assign(state.preset,{stroke:'#0066cc',width:2,fill:'#fff',fillOpacity:0,dash:'',hatch:'none',opacity:1});if(b.dataset.preset==='yellowHighlight')Object.assign(state.preset,{stroke:'#f3c000',width:1,fill:'#ffe000',fillOpacity:.45,dash:'',hatch:'none',opacity:.8});toast('Drawing default updated.')});
function renderLayers(){const box=$('#layerList');if(!box)return;box.innerHTML='';state.layers.forEach(l=>{const row=document.createElement('div');row.className='layerRow';const active=document.createElement('button');active.className=l.id===state.activeLayer?'activeLayer':'';active.textContent=l.id===state.activeLayer?'●':'○';active.title='Make active layer';active.onclick=()=>{state.activeLayer=l.id;renderLayers()};const vis=document.createElement('button');vis.textContent=l.visible===false?'◌':'◉';vis.title=l.visible===false?'Show layer':'Hide layer';vis.onclick=()=>{l.visible=l.visible===false?true:false;if(state.selected&&!isMarkupVisible(selectedMarkup()||{}))state.selected=null;render()};const lock=document.createElement('button');lock.textContent=l.locked?'🔒':'🔓';lock.title=l.locked?'Unlock layer':'Lock layer';lock.onclick=()=>{l.locked=!l.locked;renderLayers();renderSelection()};const name=document.createElement('span');name.className='layerName';name.textContent=l.name;row.append(active,vis,lock,name);box.appendChild(row)});updateProperties()}
$('#addLayer').onclick=()=>{let base='Layer',n=1;while(state.layers.some(l=>l.name===`${base} ${n}`))n++;const id='layer_'+Date.now().toString(36);state.layers.push({id,name:`${base} ${n}`,visible:true,locked:false});state.activeLayer=id;renderLayers();toast(`Created ${base} ${n}.`)};
function fillStamps(id,list,cls=''){const box=$(id);box.innerHTML='';list.forEach(t=>{const b=document.createElement('button');b.className='stampBtn '+cls;b.textContent=t;b.onclick=()=>addStamp(t);box.appendChild(b)})}fillStamps('#stampsInspection',inspection);fillStamps('#stampsSignals',signals,'blue');fillStamps('#stampsSigns',signs,'blue');fillStamps('#stampsTtc',ttc,'orange');
function renderCustomStamps(){const box=$('#stampsCustom');box.innerHTML='';state.customStamps.forEach(s=>{const b=document.createElement('button');b.className='stampBtn customStampBtn';b.innerHTML=`<img src="${s.data}" alt="${esc(s.name)}"><span>${esc(s.name)}</span>`;b.onclick=()=>addStamp(s.name.replace(/\.[^.]+$/,''),s.data,s.aspect||null);box.appendChild(b)})}try{state.customStamps=JSON.parse(localStorage.getItem('nxt_custom_stamps')||'[]')}catch{}renderCustomStamps();
function imageAspect(data){return new Promise(resolve=>{const im=new Image();im.onload=()=>resolve(im.naturalWidth&&im.naturalHeight?im.naturalWidth/im.naturalHeight:1);im.onerror=()=>resolve(1);im.src=data})}
$('#addCustomStamp').onclick=()=>$('#stampOpen').click();$('#stampOpen').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;const data=await fileDataUrl(f),aspect=await imageAspect(data);state.customStamps.push({name:f.name,data,aspect});try{localStorage.setItem('nxt_custom_stamps',JSON.stringify(state.customStamps))}catch{toast('Custom stamp added for this session; browser storage is full.')}renderCustomStamps();toast('Custom stamp artwork added to local library.')};
function trafficPreview(s){if(s.svg){const src=encodeURI(MUTCD_ASSET_BASE+s.svg);return`<div class="trafficSignPreview asset"><img class="mutcdThumb" src="${src}" alt="${esc(s.code)} ${esc(s.name)}"></div>`}const cls=s.shape==='diamond'?'diamond '+(s.background==='orange'?'orange':''):s.shape==='octagon'?'octagon':s.shape==='triangle'?'triangle':'rectangle '+(s.background==='green'?'green':s.background==='blue'?'blue':'');const text=(s.shape==='octagon'?'STOP':s.shape==='triangle'?'YIELD':s.name).split(/\s+/).slice(0,4).join(' ');return`<div class="trafficSignPreview"><div class="face ${cls}"><span>${esc(text)}</span></div></div>`}
function federalCategoryFor(code,meta){if(/^W(20|21|22|23|24|25|26)-/i.test(code))return'ttc';return meta.category||'other'}
function normalizeTrafficSearch(v){return String(v||'').toLowerCase().replace(/([a-z]+)(0*)(\d+)/g,(_,a,z,n)=>a+String(Number(n))).replace(/-(0+)(\d+)/g,'-$2').replace(/\s+/g,' ').trim()}
function localText(url){return new Promise((resolve,reject)=>{const x=new XMLHttpRequest();x.open('GET',url,true);x.onreadystatechange=()=>{if(x.readyState!==4)return;if(x.status===200||x.status===0)resolve(x.responseText);else reject(new Error('HTTP '+x.status))};x.onerror=()=>reject(new Error('Could not load '+url));x.send()})}
async function localJson(url){return JSON.parse(await localText(url))}
async function ensureMutcdLibrary(){if(state.mutcdIndex)return state.mutcdIndex;if(state.mutcdLoad)return state.mutcdLoad;state.mutcdLoad=(async()=>{try{const j=await localJson(new URL(MUTCD_ASSET_BASE+'index.json',location.href).href);state.mutcdIndex=Object.entries(j).map(([code,m])=>({code,name:m.name,category:federalCategoryFor(code,m),rawCategory:m.category,shape:m.shape,background:m.background,svg:m.svg,itemKind:'sign',source:'FHWA MUTCD 11th Ed. / 2024 Standard Highway Signs'}));return state.mutcdIndex}catch(err){console.error('Real MUTCD SVG library not found. Generated federal fallback signs are disabled.',err);state.mutcdIndex=[];return state.mutcdIndex}})();return state.mutcdLoad}
async function renderTrafficLibrary(){const q=($('#trafficSearch').value||'').trim().toLowerCase(),cat=$('#trafficCategory').value,box=$('#trafficResults');box.innerHTML='<div class="trafficLoading">Loading traffic-control library…</div>';const full=await ensureMutcdLibrary();if(!box.isConnected)return;let items=[];full.forEach(s=>items.push(s));TRAFFIC_DEVICES.forEach(s=>items.push({...s,category:'devices',itemKind:'device',source:'2025 TMUTCD Part 6 / TxDOT work-zone standards'}));TXDOT_STANDARDS.forEach(s=>items.push({...s,category:'standards',itemKind:'standard',source:'Current TxDOT Traffic Standards'}));const nq=normalizeTrafficSearch(q);items=items.filter(s=>(cat==='all'||s.category===cat)&&(!q||`${s.code} ${s.name} ${s.source||''} ${s.group||''}`.toLowerCase().includes(q)||normalizeTrafficSearch(`${s.code} ${s.name} ${s.source||''} ${s.group||''}`).includes(nq)));const limited=items.slice(0,250);box.innerHTML='';if(full.length){const badge=document.createElement('div');badge.className='trafficLibraryBadge';badge.textContent=`REAL MUTCD SVG library loaded: ${full.length.toLocaleString()} vector sign faces`;box.appendChild(badge)}else{const err=document.createElement('div');err.className='trafficAssetError';err.innerHTML='<strong>Real MUTCD SVG assets are not loaded.</strong><span>The real MUTCD asset folder is not present beside the app. Run VERIFY_MUTCD_ASSETS.bat to confirm the local library. Generated fallback federal signs are disabled in this build.</span>';box.appendChild(err)}limited.forEach(s=>{const b=document.createElement('button');if(s.itemKind==='sign'){b.className='trafficCard assetCard';b.innerHTML=trafficPreview(s)+`<span class="trafficMeta"><b>${esc(s.code)}</b><strong>${esc(s.name)}</strong><small>${esc(s.source||'')}</small></span>`;b.onclick=()=>addTrafficSign(s)}else if(s.itemKind==='device'){const glyph={cone:'▲',drum:'▥',verticalPanel:'▯',barricade:'☷',barrier:'▰',arrowBoard:'⇢',pcms:'▣',tma:'▱',flagger:'⚑',workVehicle:'▣',trafficFlow:'➜',workZone:'▧',buffer:'⋯'}[s.kind]||'◆';b.className='trafficCard deviceCard';b.innerHTML=`<span class="deviceGlyph">${glyph}</span><span class="trafficMeta"><b>${esc(s.code)}</b><strong>${esc(s.name)}</strong><small>${esc(s.source)}</small></span>`;b.onclick=()=>addTrafficDevice(s)}else{b.className='trafficCard standardCard';b.innerHTML=`<span class="trafficMeta"><b>${esc(s.code)}</b><strong>${esc(s.name)}</strong><small>${esc(s.detail||s.source||'')}</small></span>`;b.onclick=()=>addStandardNote(s)}box.appendChild(b)});const foot=document.createElement('div');foot.className='trafficMore';foot.textContent=`${items.length} matching item${items.length===1?'':'s'}${items.length>limited.length?` · showing first ${limited.length}`:''} · search by sign code or description`;box.appendChild(foot)}
$('#trafficSearch').oninput=renderTrafficLibrary;$('#trafficCategory').onchange=renderTrafficLibrary;
HATCH_LIBRARY.forEach(h=>{const o=document.createElement('option');o.value=h.id;o.textContent=`${h.family} — ${h.name}`;$('#propHatch').appendChild(o)});const none=document.createElement('option');none.value='none';none.textContent='None';$('#propHatch').insertBefore(none,$('#propHatch').firstChild);
$('#newPage').onclick=()=>$('#modalBackdrop').classList.remove('hidden');$('#cancelModal').onclick=()=>$('#modalBackdrop').classList.add('hidden');$('#createPage').onclick=()=>{checkpoint();const [w,h,name]=$('#sheetSize').value.split(',');state.pages.push(newPage(+w,+h,name));state.pageIndex=state.pages.length-1;state.selected=null;$('#modalBackdrop').classList.add('hidden');render();fitPage()};
$('#importImage').onclick=()=>$('#imageOpen').click();$('#imageOpen').onchange=async e=>{const f=e.target.files[0];if(!f)return;const data=await fileDataUrl(f),img=new Image();img.onload=()=>{checkpoint();const landscape=img.width>=img.height,p=newPage(landscape?792:612,landscape?612:792,'Imported Image');p.bg={data,name:f.name};state.pages.push(p);state.pageIndex=state.pages.length-1;render();fitPage()};img.src=data};
function fileDataUrl(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)})}
$('#btnOpen').onclick=()=>$('#fileOpen').click();
$('#fileOpen').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{if(f.name.toLowerCase().endsWith('.nxp')){await loadProject(JSON.parse(await f.text()));return}if(f.type==='application/pdf'||f.name.toLowerCase().endsWith('.pdf')){toast('Loading PDF pages…');await loadPdfBytes(new Uint8Array(await f.arrayBuffer()),f.name);closePalettes();setTool('hand');toast(`Opened ${state.pages.length}-page PDF for review.`);return}if(f.type.startsWith('image/')){$('#imageOpen').files=e.target.files;$('#imageOpen').dispatchEvent(new Event('change'))}}catch(err){console.error(err);toast('Open failed: '+(err.message||err))}};
async function saveProject(){finishInlineEdit();const data={format:'NXT Gen Plans Project',version:'0.1-R3',projectName:state.projectName,pages:state.pages,preset:state.preset,layers:state.layers,activeLayer:state.activeLayer,sourcePdf:state.pdfBytes?{name:state.pdfFileName||state.projectName,base64:bytesToBase64(state.pdfBytes)}:null};download(new Blob([JSON.stringify(data)],{type:'application/json'}),(state.projectName.replace(/\.pdf$/i,'')||'NXT_Gen_Plans')+'.nxp');toast('Editable NXT project saved.')}
$('#btnSaveProject').onclick=saveProject;
async function loadProject(d){if(!d||!Array.isArray(d.pages))return toast('Not a valid NXT project file.');const projectName=d.projectName||'NXT Gen Plans';state.projectName=projectName;state.preset={...state.preset,...(d.preset||{})};if(Array.isArray(d.layers)&&d.layers.length)state.layers=d.layers;state.activeLayer=d.activeLayer||state.layers[0]?.id||'default';state.pageIndex=0;state.selected=null;state.history=[];state.future=[];if(d.sourcePdf?.base64){toast('Restoring source PDF…');await loadPdfBytes(base64ToBytes(d.sourcePdf.base64),d.sourcePdf.name||projectName,d.pages);state.projectName=projectName;render()}else{state.pdfDoc=null;state.pdfBytes=null;state.pdfFileName=null;state.pages=d.pages;render();fitPage()}toast('Project loaded.')}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},2500)}
function openExportDialog(){$('#exportBackdrop').classList.remove('hidden')}
$('#btnExportPdf').onclick=openExportDialog;$('#cancelExport').onclick=()=>$('#exportBackdrop').classList.add('hidden');
$('#runExport').onclick=async()=>{finishInlineEdit();$('#exportBackdrop').classList.add('hidden');toast('Rendering flattened review PDF…');try{const pages=[],dpi=Number($('#exportDpi').value)||150,size=$('#exportSize').value,placement=$('#exportPlacement').value,scope=$('#exportPages').value,indices=scope==='current'?[state.pageIndex]:state.pages.map((_,i)=>i);for(let n=0;n<indices.length;n++){toast(`Rendering PDF page ${n+1} of ${indices.length}…`);pages.push(await rasterPage(indices[n],{dpi,size,placement}))}download(new Blob([buildPdf(pages)],{type:'application/pdf'}),(state.projectName.replace(/\.[^.]+$/,'')||'NXT_Gen_Plans')+'_review.pdf');toast('Adobe-compatible review PDF exported.')}catch(err){console.error(err);toast('PDF export failed: '+(err.message||err))}};
function outputSizeFor(p,size){if(!size||size==='source')return{w:p.w,h:p.h,name:p.name};const [w,h,name]=size.split(',');return{w:+w,h:+h,name}}
async function drawSvgClone(ctx,p,dx,dy,dw,dh,pdfOnlyOverlay=false){const svg=$('#pageSvg').cloneNode(true);svg.querySelector('#interactionLayer').innerHTML='';svg.setAttribute('viewBox',`0 0 ${p.w} ${p.h}`);svg.setAttribute('width',dw);svg.setAttribute('height',dh);if(pdfOnlyOverlay){const paper=svg.querySelector('.paper');if(paper)paper.setAttribute('fill','none');const bg=svg.querySelector('#backgroundLayer');if(bg)bg.innerHTML=''}const xml=new XMLSerializer().serializeToString(svg),blob=new Blob([xml],{type:'image/svg+xml'}),url=URL.createObjectURL(blob),img=new Image();await new Promise((res,rej)=>{img.onload=res;img.onerror=()=>rej(new Error('Could not rasterize NXT markup overlay'));img.src=url});ctx.drawImage(img,dx,dy,dw,dh);URL.revokeObjectURL(url)}
async function rasterPage(i,opts={}){const prev=state.pageIndex,sel=state.selected;state.pageIndex=i;state.selected=null;render();await new Promise(r=>setTimeout(r,30));const p=currentPage(),out=outputSizeFor(p,opts.size),dpi=opts.dpi||150;let pxPerPt=dpi/72,maxPixels=38_000_000,pixels=out.w*out.h*pxPerPt*pxPerPt;if(pixels>maxPixels)pxPerPt*=Math.sqrt(maxPixels/pixels);const c=document.createElement('canvas');c.width=Math.max(1,Math.round(out.w*pxPerPt));c.height=Math.max(1,Math.round(out.h*pxPerPt));const ctx=c.getContext('2d',{alpha:false});ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);const fitScale=Math.min(out.w/p.w,out.h/p.h),scale=opts.placement==='actual'?1:(opts.placement==='shrink'?Math.min(1,fitScale):fitScale),dw=p.w*scale*pxPerPt,dh=p.h*scale*pxPerPt,dx=(c.width-dw)/2,dy=(c.height-dh)/2;if(p.source?.type==='pdf'&&state.pdfDoc){const pg=await state.pdfDoc.getPage(p.source.pageNumber),vp=pg.getViewport({scale:pxPerPt*scale,rotation:p.rotation||0}),tmp=document.createElement('canvas');tmp.width=Math.max(1,Math.round(vp.width));tmp.height=Math.max(1,Math.round(vp.height));await pg.render({canvasContext:tmp.getContext('2d',{alpha:false}),viewport:vp}).promise;ctx.drawImage(tmp,dx,dy,dw,dh);await drawSvgClone(ctx,p,dx,dy,dw,dh,true)}else await drawSvgClone(ctx,p,dx,dy,dw,dh,false);const jpg=base64Bytes(c.toDataURL('image/jpeg',.94).split(',')[1]);state.pageIndex=prev;state.selected=sel;render();return{w:out.w,h:out.h,jpg,iw:c.width,ih:c.height}}
function base64Bytes(s){const bin=atob(s),a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return a}
function buildPdf(pages){const enc=new TextEncoder(),parts=[],offsets=[0];let len=0;const push=x=>{const b=typeof x==='string'?enc.encode(x):x;parts.push(b);len+=b.length};push('%PDF-1.7\n%âãÏÓ\n');const objects=[];objects[1]='<< /Type /Catalog /Pages 2 0 R >>';const kids=[];let obj=3;for(const p of pages){const pageObj=obj++,contentObj=obj++,imgObj=obj++;kids.push(`${pageObj} 0 R`);objects[pageObj]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${p.w} ${p.h}] /Resources << /XObject << /Im0 ${imgObj} 0 R >> >> /Contents ${contentObj} 0 R >>`;const stream=`q\n${p.w} 0 0 ${p.h} 0 0 cm\n/Im0 Do\nQ\n`;objects[contentObj]={dict:`<< /Length ${enc.encode(stream).length} >>`,stream:enc.encode(stream)};objects[imgObj]={dict:`<< /Type /XObject /Subtype /Image /Width ${p.iw} /Height ${p.ih} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${p.jpg.length} >>`,stream:p.jpg}}objects[2]=`<< /Type /Pages /Kids [${kids.join(' ')}] /Count ${pages.length} >>`;for(let i=1;i<objects.length;i++){offsets[i]=len;push(`${i} 0 obj\n`);const o=objects[i];if(typeof o==='string')push(o+'\nendobj\n');else{push(o.dict+'\nstream\n');push(o.stream);push('\nendstream\nendobj\n')}}const xref=len;push(`xref\n0 ${objects.length}\n0000000000 65535 f \n`);for(let i=1;i<objects.length;i++)push(String(offsets[i]).padStart(10,'0')+' 00000 n \n');push(`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`);const outb=new Uint8Array(len);let pos=0;for(const b of parts){outb.set(b,pos);pos+=b.length}return outb}
function setZoom(z){state.zoom=Math.max(.05,Math.min(8,z));const zt=Math.round(state.zoom*100)+'%';$('#zoomSelect').value=[...$('#zoomSelect').options].some(o=>o.value===zt)?zt:'';render()}
function fitPage(){const p=currentPage(),a=$('#canvasScroller');setZoom(Math.min((a.clientWidth-55)/(p.w*96/72),(a.clientHeight-55)/(p.h*96/72)))}function fitWidth(){const p=currentPage(),a=$('#canvasScroller');setZoom((a.clientWidth-45)/(p.w*96/72))}
$('#zoomIn').onclick=()=>setZoom(state.zoom*1.25);$('#zoomOut').onclick=()=>setZoom(state.zoom/1.25);$('#fitPage').onclick=fitPage;$('#fitWidth').onclick=fitWidth;$('#actualSize').onclick=()=>setZoom(1);$('#zoomSelect').onchange=e=>{const n=parseFloat(e.target.value);if(n)setZoom(n/100)};
const sc=$('#canvasScroller');sc.addEventListener('pointerdown',e=>{if(state.tool!=='hand'||e.button!==0)return;state.pan={x:e.clientX,y:e.clientY,l:sc.scrollLeft,t:sc.scrollTop};sc.classList.add('panning');e.preventDefault()});window.addEventListener('pointermove',e=>{if(!state.pan)return;sc.scrollLeft=state.pan.l-(e.clientX-state.pan.x);sc.scrollTop=state.pan.t-(e.clientY-state.pan.y)});window.addEventListener('pointerup',()=>{state.pan=null;sc.classList.remove('panning')});sc.addEventListener('wheel',e=>{if(e.ctrlKey){e.preventDefault();const old=state.zoom,r=sc.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top;setZoom(state.zoom*(e.deltaY<0?1.12:.89));const ratio=state.zoom/old;sc.scrollLeft=(sc.scrollLeft+mx)*ratio-mx;sc.scrollTop=(sc.scrollTop+my)*ratio-my}},{passive:false});
function updateStatus(){const p=currentPage();$('#statusPage').textContent=`Page ${state.pageIndex+1} / ${state.pages.length}`;$('#statusSize').textContent=p.name;$('#statusZoom').textContent=Math.round(state.zoom*100)+'%';$('#docTitle').textContent=state.projectName}

function copySelected(){const m=selectedMarkup();if(!m)return toast('Select a markup first.');state.clipboard=JSON.parse(JSON.stringify(m));toast('Markup copied.')}
function pasteSelected(){if(!state.clipboard)return toast('Nothing copied.');checkpoint();const c=JSON.parse(JSON.stringify(state.clipboard)),orig=JSON.parse(JSON.stringify(state.clipboard));c.id=uid();translateMarkup(c,16,16,orig);c.subject=(c.subject||'Markup')+' Copy';c.created=c.modified=new Date().toISOString();currentPage().markups.push(c);state.selected=c.id;render();setTool('select')}
function nextPage(delta){const n=Math.max(0,Math.min(state.pages.length-1,state.pageIndex+delta));if(n===state.pageIndex)return;state.pageIndex=n;state.selected=null;render();fitPage()}
function duplicatePage(){checkpoint();const p=JSON.parse(JSON.stringify(currentPage()));p.id=uid();p.markups.forEach(m=>m.id=uid());state.pages.splice(state.pageIndex+1,0,p);state.pageIndex++;state.selected=null;render();fitPage()}
function deletePage(){if(state.pages.length<=1)return toast('A document must contain at least one page.');checkpoint();state.pages.splice(state.pageIndex,1);state.pageIndex=Math.min(state.pageIndex,state.pages.length-1);state.selected=null;render();fitPage()}
function rotatePoint90(x,y,h){return[h-y,x]}
function rotateMarkup90(m,h){if(LINE_TYPES.includes(m.type)){[m.x,m.y]=rotatePoint90(m.x,m.y,h);[m.x2,m.y2]=rotatePoint90(m.x2,m.y2,h)}else if(POLY_TYPES.includes(m.type)||m.type==='freehand'){m.points=m.points.map(([x,y])=>rotatePoint90(x,y,h));if(m.type==='freehand')rebuildFreehand(m)}else{const pts=[[m.x,m.y],[m.x+(m.w||0),m.y],[m.x+(m.w||0),m.y+(m.h||0)],[m.x,m.y+(m.h||0)]].map(([x,y])=>rotatePoint90(x,y,h)),xs=pts.map(a=>a[0]),ys=pts.map(a=>a[1]);m.x=Math.min(...xs);m.y=Math.min(...ys);m.w=Math.max(...xs)-m.x;m.h=Math.max(...ys)-m.y}m.rotation=((m.rotation||0)+90)%360}
function rotateCurrentPage(dir=1){checkpoint();const p=currentPage(),times=dir>0?1:3;for(let n=0;n<times;n++){const oldH=p.h;p.markups.forEach(m=>rotateMarkup90(m,oldH));[p.w,p.h]=[p.h,p.w];p.rotation=((p.rotation||0)+90)%360}render();fitPage()}
function highlightTextSelection(){const sel=window.getSelection();if(!sel||sel.isCollapsed)return toast('Select PDF text first.');const stage=$('#pageStage').getBoundingClientRect(),sc=96/72*state.zoom,rects=[...sel.getRangeAt(0).getClientRects()].filter(r=>r.width>1&&r.height>1);if(!rects.length)return toast('No text selection found.');checkpoint();for(const r of rects){const x=(r.left-stage.left)/sc,y=(r.top-stage.top)/sc,w=r.width/sc,h=r.height/sc;if(x<currentPage().w&&y<currentPage().h&&x+w>0&&y+h>0){currentPage().markups.push({...baseMarkup('highlight',{x,y}),x,y,w,h,fill:'#ffe000',fillOpacity:.42,stroke:'none',width:0,subject:'Text Highlight',layer:'comments'})}}sel.removeAllRanges();render();setTool('select');toast('Text selection highlighted.')}
function openHelp(kind='shortcuts'){const title=$('#helpTitle'),body=$('#helpBody');if(kind==='about'){title.textContent='About NXT Gen Plans 0.1 R3';body.innerHTML='<p>Offline civil construction-plan review workspace for PDF and image plan sets.</p><p>R3 uses a locally bundled PDF.js rendering engine, editable NXT markup overlays, a full MUTCD SVG integration when the bundled sign folder is present, and flattened PDF 1.7 review export.</p>'}else{title.textContent='Keyboard Shortcuts';body.innerHTML='<div class="shortcutGrid"><b>H</b><span>Hand / Pan</span><b>V</b><span>Select markup</span><b>Z</b><span>Marquee Zoom</span><b>Space</b><span>Temporary Hand</span><b>Ctrl+O</b><span>Open</span><b>Ctrl+S</b><span>Save NXT Project</span><b>Ctrl+P</b><span>Export / Print PDF</span><b>Ctrl+Z / Ctrl+Y</b><span>Undo / Redo</span><b>Ctrl+C / Ctrl+V</b><span>Copy / Paste markup</span><b>Ctrl+D</b><span>Duplicate markup</span><b>Ctrl+0</b><span>Fit Page</span><b>Ctrl+1</b><span>Actual Size</span><b>Ctrl+2</b><span>Fit Width</span><b>Page Up / Down</b><span>Previous / Next page</span></div>'}$('#helpBackdrop').classList.remove('hidden')}
$('#closeHelp').onclick=()=>$('#helpBackdrop').classList.add('hidden');
function closeMenus(){$('#menuHost').innerHTML='';$$('#menuBar [data-menu]').forEach(b=>b.classList.remove('active'))}
const MENUS={
 file:[['Open…','Ctrl+O',()=>$('#fileOpen').click()],['Save NXT Project','Ctrl+S',saveProject],['Export / Print PDF…','Ctrl+P',openExportDialog],['-', '',null],['New Blank Sheet','',()=>$('#modalBackdrop').classList.remove('hidden')],['Import Image…','',()=>$('#imageOpen').click()]],
 edit:[['Undo','Ctrl+Z',undo],['Redo','Ctrl+Y',redo],['-', '',null],['Copy Markup','Ctrl+C',copySelected],['Paste Markup','Ctrl+V',pasteSelected],['Duplicate Markup','Ctrl+D',duplicateSelected],['Delete Markup','Del',deleteSelected]],
 view:[['Fit Page','Ctrl+0',fitPage],['Actual Size','Ctrl+1',()=>setZoom(1)],['Fit Width','Ctrl+2',fitWidth],['Zoom In','Ctrl++',()=>setZoom(state.zoom*1.25)],['Zoom Out','Ctrl+-',()=>setZoom(state.zoom/1.25)],['-', '',null],['Pages','',()=>togglePalette('pagesPalette')],['Markups & Notes','',()=>togglePalette('markupsPalette')],['Full Screen','F11',()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen()]],
 document:[['Insert Blank Sheet','',()=>$('#modalBackdrop').classList.remove('hidden')],['Duplicate Page','',duplicatePage],['Delete Page','',deletePage],['Rotate Page Clockwise','',()=>rotateCurrentPage(1)],['Rotate Page Counterclockwise','',()=>rotateCurrentPage(-1)],['-', '',null],['Previous Page','Page Up',()=>nextPage(-1)],['Next Page','Page Down',()=>nextPage(1)]],
 tools:[['Hand','H',()=>setTool('hand')],['Select','V',()=>setTool('select')],['Marquee Zoom','Z',()=>setTool('zoom')],['PDF Text Select','',()=>setTool('textselect')],['Highlight Selected PDF Text','',highlightTextSelection],['-', '',null],['Drawing & Markup Tools','',()=>togglePalette('toolPalette')],['Stamps','',()=>togglePalette('stampsPalette')],['Texas Traffic Control','',()=>togglePalette('trafficPalette')]],
 window:[['Properties','',()=>openPropertiesAt(null,selectedMarkup()?'object':'tool',state.tool)],['Layers','',()=>togglePalette('layersPalette')],['Pages','',()=>togglePalette('pagesPalette')],['Markups & Notes','',()=>togglePalette('markupsPalette')],['Close Floating Panels','',()=>closePalettes()]],
 help:[['Keyboard Shortcuts','',()=>openHelp('shortcuts')],['About NXT Gen Plans','',()=>openHelp('about')]]
};
function openMenu(btn){const key=btn.dataset.menu;closeMenus();btn.classList.add('active');const host=$('#menuHost'),drop=document.createElement('div');drop.className='menuDrop';const r=btn.getBoundingClientRect();drop.style.left=r.left+'px';drop.style.top=r.bottom+'px';for(const [label,keyText,action] of MENUS[key]||[]){if(label==='-'){drop.appendChild(document.createElement('hr'));continue}const item=document.createElement('button');item.className='menuItem';item.innerHTML=`<span>${esc(label)}</span><kbd>${esc(keyText)}</kbd>`;item.onclick=e=>{e.stopPropagation();closeMenus();action?.()};drop.appendChild(item)}host.appendChild(drop)}
$$('#menuBar [data-menu]').forEach(b=>b.onclick=e=>{e.stopPropagation();if(b.classList.contains('active'))closeMenus();else openMenu(b)});

function csvCell(v){const s=String(v??'');return /[",\n\r]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s}
function exportMarkupCsv(){const rows=[['Page','Page Name','Type','Subject','Status','Comment','Layer','Created','Modified']];state.pages.forEach((p,pi)=>p.markups.forEach(m=>rows.push([pi+1,p.name||'',m.type||'',m.subject||'',m.status||'',m.comment||'',layerById(m.layer).name||m.layer||'',m.created||'',m.modified||''])));if(rows.length===1)return toast('No markups to export.');const csv='\ufeff'+rows.map(r=>r.map(csvCell).join(',')).join('\r\n');download(new Blob([csv],{type:'text/csv;charset=utf-8'}),(state.projectName.replace(/\.[^.]+$/,'')||'NXT_Gen_Plans')+'_markups.csv');toast(`Exported ${rows.length-1} markup records to CSV.`)}
$('#exportMarkupCsv').onclick=exportMarkupCsv;
$('#markupFilter').oninput=renderTable;
document.addEventListener('pointerdown',e=>{if(e.target.closest('.palette,.contextMenu,[data-palette],#btnProperties,#mainToolbar,.menubar,.menuHost,.modalBackdrop'))return;closePalettes();$('#contextMenu').classList.add('hidden')});document.addEventListener('click',e=>{if(!e.target.closest('#contextMenu'))$('#contextMenu').classList.add('hidden');if(!e.target.closest('.menubar,.menuHost'))closeMenus()});
window.addEventListener('keydown',e=>{const tag=document.activeElement?.tagName,inputActive=['INPUT','TEXTAREA','SELECT'].includes(tag)&&document.activeElement!==$('#inlineEditor');if(e.code==='Space'&&!e.repeat&&!state.editing&&!inputActive){state.previousTool=state.tool;setTool('hand');e.preventDefault()}if(inputActive)return;if(e.ctrlKey&&e.key.toLowerCase()==='o'){e.preventDefault();$('#fileOpen').click()}else if(e.ctrlKey&&e.key.toLowerCase()==='s'){e.preventDefault();saveProject()}else if(e.ctrlKey&&e.key.toLowerCase()==='p'){e.preventDefault();openExportDialog()}else if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();undo()}else if(e.ctrlKey&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}else if(e.ctrlKey&&e.key.toLowerCase()==='c'&&!state.editing){e.preventDefault();copySelected()}else if(e.ctrlKey&&e.key.toLowerCase()==='v'&&!state.editing){e.preventDefault();pasteSelected()}else if(e.ctrlKey&&e.key.toLowerCase()==='d'&&!state.editing){e.preventDefault();duplicateSelected()}else if(e.ctrlKey&&(e.key==='='||e.key==='+')){setZoom(state.zoom*1.25);e.preventDefault()}else if(e.ctrlKey&&e.key==='-'){setZoom(state.zoom/1.25);e.preventDefault()}else if(e.ctrlKey&&e.key==='0'){fitPage();e.preventDefault()}else if(e.ctrlKey&&e.key==='1'){setZoom(1);e.preventDefault()}else if(e.ctrlKey&&e.key==='2'){fitWidth();e.preventDefault()}else if(e.key==='PageDown'){e.preventDefault();nextPage(1)}else if(e.key==='PageUp'){e.preventDefault();nextPage(-1)}else if(!e.ctrlKey&&!e.altKey&&!state.editing){if(e.key.toLowerCase()==='h')setTool('hand');if(e.key.toLowerCase()==='v')setTool('select');if(e.key.toLowerCase()==='z')setTool('zoom')}if(e.key==='Escape'){closeMenus();if(state.editing)finishInlineEdit();else{closePalettes();$('#contextMenu').classList.add('hidden');finishPolyDraft(false);setTool('hand')}}if(e.key==='Delete'&&state.selected&&!state.editing)deleteSelected()});window.addEventListener('keyup' ,e=>{if(e.code==='Space'&&state.previousTool){const t=state.previousTool;state.previousTool=null;setTool(t)}});window.addEventListener('resize',()=>{closePalettes();requestAnimationFrame(fitPage)});
renderTrafficLibrary();render();requestAnimationFrame(fitPage);setTool('hand');closePalettes();
