'use strict';
const NS='http://www.w3.org/2000/svg';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const TEXT_TYPES=['text','textbox','note'];
const BOX_TYPES=['rect','square','ellipse','circle','cloud','hatch','highlight','textbox','note','stamp','trafficSign','device'];
const LINE_TYPES=['line','arrow','measure','callout','deviceRun'];
const POLY_TYPES=['polygon','polyline','cloudFree','hatchFree'];
const state={tool:'hand',previousTool:null,zoom:1,pages:[],pageIndex:0,selected:null,drawing:null,pan:null,pdfMode:false,projectName:'Untitled Plan',polyDraft:null,editing:null,propertyMode:'object',propertyTool:null,customStamps:[],layers:[{id:'default',name:'Default',visible:true,locked:false},{id:'comments',name:'Review / Comments',visible:true,locked:false},{id:'traffic',name:'Traffic Control',visible:true,locked:false},{id:'measurements',name:'Measurements',visible:true,locked:false}],activeLayer:'default',preset:{stroke:'#d71920',width:2,fill:'#ffffff',fillOpacity:0,dash:'',hatch:'none',hatchColor:'#d71920',hatchSpacing:10,opacity:1,rotation:0,font:'Arial',fontSize:14,textColor:'#111111',textAlign:'left',bold:false,italic:false}};
const inspection=['FIELD VISIT PENDING','FIELD VISIT REQUIRED','FIELD INSPECTION REQUIRED','PASSED INSPECTION','PASSED PRE-POUR INSPECTION','PASSED PRE-PAVE INSPECTION','REINSPECTION REQUIRED','CORRECTIONS REQUIRED','FIELD VERIFIED'];
const signals=['SIGNAL INSPECTION REQUIRED','SIGNAL INSPECTION PASSED','SIGNAL INSTALLATION PENDING','SIGNAL INSTALLATION VERIFIED','SIGNAL ACTIVATION PENDING','SIGNAL WORK REQUIRES CORRECTION'];
const signs=['SIGN INSPECTION REQUIRED','SIGN INSTALLATION VERIFIED','SIGN PLACEMENT CORRECTION REQUIRED','SIGN MISSING','SIGN RELOCATION REQUIRED','SIGN REPLACEMENT REQUIRED'];
const ttc=['TTC INSPECTION REQUIRED','TTC APPROVED','TTC CORRECTION REQUIRED','TTC SETUP VERIFIED','TTC REVISION REQUIRED','DEVICE PLACEMENT CORRECTION REQUIRED','MISSING TTC DEVICE','BARRICADE / CHANNELIZING DEVICE CORRECTION','TRAFFIC CONTROL NOT PER PLAN','TRAFFIC CONTROL FIELD ADJUSTMENT REQUIRED'];
function uid(){return 'm'+Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function newPage(w=792,h=612,name='ANSI A Landscape'){return{id:uid(),w,h,name,bg:null,markups:[]}}
state.pages=[newPage()];
function currentPage(){return state.pages[state.pageIndex]}
function selectedMarkup(){return currentPage()?.markups.find(m=>m.id===state.selected)||null}
function layerById(id){return state.layers.find(l=>l.id===(id||'default'))||state.layers[0]}
function isMarkupVisible(m){return layerById(m.layer).visible!==false}
function isMarkupLocked(m){return !!m.locked||!!layerById(m.layer).locked}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');clearTimeout(t._tm);t._tm=setTimeout(()=>t.classList.add('hidden'),2600)}
function toolLabel(t){return({hand:'Hand',select:'Select',zoom:'Marquee Zoom',textselect:'Text Select',rect:'Rectangle',square:'Square',ellipse:'Ellipse',circle:'Circle',polygon:'Polygon',polyline:'Polyline',line:'Line',arrow:'Arrow',freehand:'Pen',highlight:'Highlight',cloud:'Cloud Box',cloudFree:'Freeform Cloud',hatch:'Hatch Box',hatchFree:'Freeform Hatch',text:'Text Line',textbox:'Text Box',note:'Note Box',callout:'Callout',measure:'Measure',deviceRun:'Device Run'})[t]||t}
function setTool(tool){if(state.pdfMode&&!['hand','textselect','zoom'].includes(tool)){toast('Imported PDF is in native-view mode in 0.1. Return to Plan Canvas for NXT markups.');return}if(state.polyDraft&&state.tool!==tool)finishPolyDraft(false);state.tool=tool;$$('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));$('#statusTool').textContent=toolLabel(tool);$('#canvasScroller').style.cursor=tool==='hand'?'grab':tool==='zoom'?'crosshair':tool==='textselect'||TEXT_TYPES.includes(tool)?'text':'crosshair';$('#pageStage').classList.toggle('textSelect',tool==='textselect')}
function style(){return JSON.parse(JSON.stringify(state.preset))}
function render(){const p=currentPage(),svg=$('#pageSvg');svg.setAttribute('viewBox',`0 0 ${p.w} ${p.h}`);const sc=96/72*state.zoom;svg.style.width=p.w*sc+'px';svg.style.height=p.h*sc+'px';$('#pageStage').style.width=svg.style.width;$('#pageStage').style.height=svg.style.height;$('.paper').setAttribute('width',p.w);$('.paper').setAttribute('height',p.h);renderBackground();renderMarkups();renderPages();renderTable();updateStatus();updateProperties();if(state.editing)positionInlineEditor()}
function renderBackground(){const g=$('#backgroundLayer');g.innerHTML='';const p=currentPage();if(p.bg){const im=document.createElementNS(NS,'image');im.setAttribute('href',p.bg.data);im.setAttribute('x',0);im.setAttribute('y',0);im.setAttribute('width',p.w);im.setAttribute('height',p.h);im.setAttribute('preserveAspectRatio','xMidYMid meet');g.appendChild(im)}}
function clearDynamicPatterns(){$$('#svgDefs [data-dyn="1"]').forEach(n=>n.remove())}
function ensureHatchPattern(m){if(!m.hatch||m.hatch==='none')return null;const defs=$('#svgDefs'),id='pat_'+m.id.replace(/[^a-z0-9_]/gi,'_');if($('#'+id))return id;const p=document.createElementNS(NS,'pattern');p.id=id;p.dataset.dyn='1';p.setAttribute('patternUnits','userSpaceOnUse');const s=Math.max(3,Number(m.hatchSpacing)||10);p.setAttribute('width',s);p.setAttribute('height',s);const bg=document.createElementNS(NS,'rect');bg.setAttribute('width',s);bg.setAttribute('height',s);bg.setAttribute('fill',m.fill||'#fff');bg.setAttribute('fill-opacity',m.fillOpacity??0);p.appendChild(bg);const c=m.hatchColor||m.stroke||'#000',w=Math.max(.5,Math.min(4,(m.width||1)*.65));const path=(d,sw=w)=>{const x=document.createElementNS(NS,'path');x.setAttribute('d',d);x.setAttribute('stroke',c);x.setAttribute('stroke-width',sw);x.setAttribute('fill','none');x.setAttribute('opacity',m.opacity??1);p.appendChild(x)};const circ=(cx,cy,r,fill=c)=>{const x=document.createElementNS(NS,'circle');x.setAttribute('cx',cx);x.setAttribute('cy',cy);x.setAttribute('r',r);x.setAttribute('fill',fill);p.appendChild(x)};
 switch(m.hatch){
  case'diag45':p.setAttribute('patternTransform','rotate(45)');path(`M0 0V${s}`);break;case'diag135':p.setAttribute('patternTransform','rotate(135)');path(`M0 0V${s}`);break;
  case'cross45':path(`M0 ${s}L${s} 0M0 0L${s} ${s}`);break;case'horizontal':path(`M0 ${s/2}H${s}`);break;case'vertical':path(`M${s/2} 0V${s}`);break;case'grid':path(`M0 ${s/2}H${s}M${s/2} 0V${s}`);break;case'dots':circ(s/2,s/2,Math.max(1,s*.1));break;
  case'earth':path(`M0 ${s*.65} Q${s*.25} ${s*.35} ${s*.5} ${s*.65}T${s} ${s*.65}`,.8);circ(s*.18,s*.22,.7);circ(s*.72,s*.22,.7);break;
  case'sand':circ(s*.2,s*.25,.65);circ(s*.7,s*.2,.8);circ(s*.5,s*.7,.6);circ(s*.88,s*.72,.5);break;
  case'gravel':path(`M1 ${s*.4}L${s*.28} 1L${s*.5} ${s*.38}L${s*.8} ${s*.12}L${s-1} ${s*.55}L${s*.6} ${s-1}L${s*.3} ${s*.65}Z`,.7);break;
  case'concrete':path(`M1 1L${s*.3} ${s*.25}L${s*.12} ${s*.55}M${s*.65} ${s*.12}L${s*.9} ${s*.35}L${s*.7} ${s*.65}M${s*.2} ${s*.85}L${s*.45} ${s*.62}`,.65);circ(s*.52,s*.35,.6);break;
  case'riprap':path(`M1 ${s*.3}L${s*.35} 1L${s*.65} ${s*.28}L${s-1} ${s*.12}L${s*.82} ${s*.7}L${s*.48} ${s-1}L${s*.18} ${s*.72}Z`,.8);break;
  case'asphalt':for(let i=0;i<7;i++)circ((i*3.7%s),((i*5.1+2)%s),.55);break;
  case'demo':p.setAttribute('patternTransform','rotate(45)');path(`M0 0V${s}`,1.4);path(`M${s/2} 0V${s}`,.5);break;case'proposed':p.setAttribute('patternTransform','rotate(45)');path(`M0 0V${s}`,.9);break;case'existing':path(`M0 ${s/2}H${s}`,.7);break;
 }
 defs.appendChild(p);return id}
function commonAttrs(el,m){el.dataset.id=m.id;el.classList.add('markup');el.setAttribute('stroke',m.stroke||'none');el.setAttribute('stroke-width',m.width??2);el.setAttribute('opacity',m.opacity??1);if(m.dash)el.setAttribute('stroke-dasharray',m.dash);const pat=ensureHatchPattern(m);let fill=pat?`url(#${pat})`:(m.fill||'none');el.setAttribute('fill',fill);if(!pat&&fill!=='none')el.setAttribute('fill-opacity',m.fillOpacity??0);if(m.rotation){const b=bounds(m);if(b)el.setAttribute('transform',`rotate(${m.rotation} ${b.x+b.w/2} ${b.y+b.h/2})`)}if(state.selected===m.id)el.classList.add('selected');el.addEventListener('pointerdown',e=>objectPointerDown(e,m));el.addEventListener('contextmenu',e=>openContext(e,m.id));if(TEXT_TYPES.includes(m.type))el.addEventListener('dblclick',e=>{e.stopPropagation();editText(m)});return el}
function svgEl(tag,attrs={}){const e=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));return e}
function wrapText(text,w,fontSize){const max=Math.max(3,Math.floor(Math.max(20,w)/(Math.max(6,fontSize)*.57))),words=String(text||'').split(/\s+/),lines=[];let line='';for(const word of words){const test=line?line+' '+word:word;if(test.length>max&&line){lines.push(line);line=word}else line=test}if(line||!lines.length)lines.push(line);return lines}
function renderTextBlock(g,m){if(state.editing===m.id)return;const fs=m.fontSize||14,lines=wrapText(m.text||'',m.w||180,fs),tx=svgEl('text',{'font-size':fs,'font-family':m.font||'Arial','font-weight':m.bold?'700':'400','font-style':m.italic?'italic':'normal',fill:m.textColor||m.stroke||'#111'});let anchor='start',x=m.x+4;if(m.textAlign==='center'){anchor='middle';x=m.x+m.w/2}else if(m.textAlign==='right'){anchor='end';x=m.x+m.w-4}tx.setAttribute('text-anchor',anchor);lines.slice(0,Math.max(1,Math.floor((m.h||40)/(fs*1.18)))).forEach((ln,i)=>{const t=svgEl('tspan',{x,dy:i===0?fs+3:fs*1.18});if(i===0)t.setAttribute('y',m.y);t.textContent=ln;tx.appendChild(t)});tx.dataset.id=m.id;tx.classList.add('markup');tx.addEventListener('pointerdown',e=>objectPointerDown(e,m));tx.addEventListener('contextmenu',e=>openContext(e,m.id));tx.addEventListener('dblclick',e=>{e.stopPropagation();editText(m)});g.appendChild(tx)}
function renderTrafficSign(g,m){const group=svgEl('g');commonAttrs(group,m);const x=m.x,y=m.y,w=m.w,h=m.h,bg=m.signBg||'white',shape=m.signShape||'rectangle';let face;const fill=bg==='orange'?'#f5a623':bg==='yellow'?'#ffd32a':bg==='green'?'#168348':bg==='blue'?'#1768ad':bg.includes('red')?'#c9222c':'#fff',stroke=bg.includes('red')?'#fff':'#111';if(shape==='diamond'){face=svgEl('rect',{x:x+w*.15,y:y+h*.15,width:w*.7,height:h*.7,fill,stroke,'stroke-width':2,transform:`rotate(45 ${x+w/2} ${y+h/2})`})}else if(shape==='octagon'){const pts=[[.29,0],[.71,0],[1,.29],[1,.71],[.71,1],[.29,1],[0,.71],[0,.29]].map(([a,b])=>`${x+a*w},${y+b*h}`).join(' ');face=svgEl('polygon',{points:pts,fill:'#c9222c',stroke:'#fff','stroke-width':3})}else if(shape==='triangle'){const pts=`${x+w/2},${y+h} ${x},${y+h*.08} ${x+w},${y+h*.08}`;face=svgEl('polygon',{points:pts,fill:'#fff',stroke:'#c9222c','stroke-width':4})}else{face=svgEl('rect',{x,y,width:w,height:h,rx:2,fill,stroke,'stroke-width':2})}group.appendChild(face);const dark=(bg==='green'||bg==='blue'||shape==='octagon')?'#fff':'#111',fs=Math.max(6,Math.min(13,Math.min(w,h)*.15)),lines=wrapText(m.signName||m.text||m.subject,w*.85,fs).slice(0,3),tx=svgEl('text',{x:x+w/2,y:y+h/2-(lines.length-1)*fs*.55,'text-anchor':'middle','font-size':fs,'font-weight':'800',fill:dark});lines.forEach((ln,i)=>{const t=svgEl('tspan',{x:x+w/2,dy:i?fs*1.05:0});t.textContent=ln.toUpperCase();tx.appendChild(t)});group.appendChild(tx);if(m.showCode!==false){const lab=svgEl('text',{x:x+w/2,y:y+h+9,'text-anchor':'middle','font-size':7,fill:'#222'});lab.textContent=m.signCode||'';group.appendChild(lab)}g.appendChild(group)}
function renderDevice(g,m){const group=svgEl('g');commonAttrs(group,m);const x=m.x,y=m.y,w=m.w,h=m.h,k=m.deviceKind||'cone';if(k==='cone'){group.appendChild(svgEl('path',{d:`M${x+w/2} ${y} L${x+w} ${y+h} L${x} ${y+h} Z`,fill:'#f58220',stroke:'#222','stroke-width':1}));group.appendChild(svgEl('rect',{x:x-2,y:y+h-3,width:w+4,height:4,fill:'#333'}))}else if(k==='drum'){group.appendChild(svgEl('rect',{x:x+w*.15,y:y,width:w*.7,height:h,rx:w*.15,fill:'#f58220',stroke:'#222','stroke-width':1}));group.appendChild(svgEl('rect',{x:x+w*.15,y:y+h*.38,width:w*.7,height:h*.18,fill:'#fff'}))}else if(k==='verticalPanel'){group.appendChild(svgEl('rect',{x:x+w*.3,y:y,width:w*.4,height:h,fill:'#fff',stroke:'#222'}));for(let i=0;i<3;i++)group.appendChild(svgEl('path',{d:`M${x+w*.3} ${y+i*h/3}L${x+w*.7} ${y+(i+1)*h/3}`,stroke:'#f58220','stroke-width':4}))}else if(k==='barricade'){[.2,.48,.76].forEach(q=>{group.appendChild(svgEl('rect',{x,y:y+h*q,width:w,height:h*.13,fill:'#fff',stroke:'#333'}));group.appendChild(svgEl('path',{d:`M${x} ${y+h*q}L${x+w} ${y+h*(q+.13)}`,stroke:'#f58220','stroke-width':5}))});group.appendChild(svgEl('line',{x1:x+w*.15,y1:y+h*.2,x2:x+w*.1,y2:y+h,stroke:'#333','stroke-width':3}));group.appendChild(svgEl('line',{x1:x+w*.85,y1:y+h*.2,x2:x+w*.9,y2:y+h,stroke:'#333','stroke-width':3}))}else if(k==='barrier'){group.appendChild(svgEl('path',{d:`M${x+w*.1} ${y}H${x+w*.9}L${x+w} ${y+h}H${x}Z`,fill:'#ddd',stroke:'#555','stroke-width':1}))}else{group.appendChild(svgEl('rect',{x,y,width:w,height:h,rx:2,fill:'#fff',stroke:'#222','stroke-width':1.5}));const t=svgEl('text',{x:x+w/2,y:y+h/2+3,'text-anchor':'middle','font-size':Math.max(6,h*.2),'font-weight':'700'});t.textContent=m.deviceCode||k.toUpperCase();group.appendChild(t)}g.appendChild(group)}
function renderMarkups(){clearDynamicPatterns();const g=$('#markupLayer');g.innerHTML='';for(const m of currentPage().markups){if(!isMarkupVisible(m))continue;let el;if(['rect','square','highlight','hatch'].includes(m.type)){el=svgEl('rect',{x:m.x,y:m.y,width:m.w,height:m.h});commonAttrs(el,m);g.appendChild(el)}else if(['ellipse','circle'].includes(m.type)){el=svgEl('ellipse',{cx:m.x+m.w/2,cy:m.y+m.h/2,rx:Math.abs(m.w/2),ry:Math.abs(m.h/2)});commonAttrs(el,m);g.appendChild(el)}else if(['textbox','note','text'].includes(m.type)){el=svgEl('rect',{x:m.x,y:m.y,width:m.w,height:m.h,rx:m.type==='note'?3:0});commonAttrs(el,m);if(m.type==='text'&&m.width===0)el.setAttribute('stroke','none');g.appendChild(el);renderTextBlock(g,m)}else if(m.type==='stamp'){el=svgEl('g');commonAttrs(el,m);const r=svgEl('rect',{x:m.x,y:m.y,width:m.w,height:m.h,rx:2,fill:'#fff',stroke:m.stroke,'stroke-width':m.width});const tx=svgEl('text',{x:m.x+m.w/2,y:m.y+m.h/2+4,'text-anchor':'middle','font-size':Math.max(7,Math.min(14,m.h*.26)),'font-weight':'800',fill:m.stroke});tx.textContent=m.text;el.append(r,tx);g.appendChild(el)}else if(m.type==='trafficSign'){renderTrafficSign(g,m)}else if(m.type==='device'){renderDevice(g,m)}else if(LINE_TYPES.includes(m.type)){el=svgEl('line',{x1:m.x,y1:m.y,x2:m.x2,y2:m.y2});commonAttrs(el,m);el.setAttribute('fill','none');if(['arrow','callout'].includes(m.type))el.setAttribute('marker-end','url(#arrowHead)');if(m.startArrow)el.setAttribute('marker-start','url(#arrowStart)');g.appendChild(el);if(m.type==='measure'){const tx=svgEl('text',{x:(m.x+m.x2)/2,y:(m.y+m.y2)/2-5,'font-size':10,fill:m.stroke});tx.textContent=distanceText(m);g.appendChild(tx)}if(m.type==='deviceRun')renderDeviceRun(g,m)}else if(m.type==='freehand'){el=svgEl('path',{d:m.d});commonAttrs(el,m);el.setAttribute('fill','none');g.appendChild(el)}else if(POLY_TYPES.includes(m.type)){if(m.points?.length){const points=m.points.map(p=>p.join(',')).join(' ');if(m.type==='cloudFree'){el=svgEl('path',{d:cloudPolygonPath(m.points)});commonAttrs(el,m);g.appendChild(el)}else if(m.type==='polyline'){el=svgEl('polyline',{points,fill:'none'});commonAttrs(el,m);el.setAttribute('fill','none');g.appendChild(el)}else{el=svgEl('polygon',{points});commonAttrs(el,m);g.appendChild(el)}}}else if(m.type==='cloud'){el=svgEl('path',{d:cloudRectPath(m.x,m.y,m.w,m.h)});commonAttrs(el,m);g.appendChild(el)}
 }renderSelection()}
function distanceText(m){return Math.hypot(m.x2-m.x,m.y2-m.y).toFixed(1)+' pt'}
function renderDeviceRun(g,m){const len=Math.hypot(m.x2-m.x,m.y2-m.y),step=Math.max(12,Number(m.deviceSpacing)||30),n=Math.max(1,Math.floor(len/step));for(let i=0;i<=n;i++){const t=i/n,cx=m.x+(m.x2-m.x)*t,cy=m.y+(m.y2-m.y)*t,d={id:m.id+'_d'+i,type:'device',x:cx-6,y:cy-8,w:12,h:16,deviceKind:m.deviceKind||'cone',deviceCode:m.deviceCode||'CONE',stroke:'#222',width:1,fill:'#f58220',fillOpacity:1,opacity:1};renderDevice(g,d)}}
function bounds(m){if(LINE_TYPES.includes(m.type))return{x:Math.min(m.x,m.x2),y:Math.min(m.y,m.y2),w:Math.abs(m.x2-m.x),h:Math.abs(m.y2-m.y)};if(m.type==='freehand')return m.bounds||null;if(POLY_TYPES.includes(m.type)){if(!m.points?.length)return null;const xs=m.points.map(p=>p[0]),ys=m.points.map(p=>p[1]);return{x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...xs)-Math.min(...xs),h:Math.max(...ys)-Math.min(...ys)}}return{x:m.x,y:m.y,w:m.w||1,h:m.h||1}}
function renderSelection(){const ig=$('#interactionLayer');ig.innerHTML='';const m=selectedMarkup();if(!m)return;const b=bounds(m);if(!b)return;const r=svgEl('rect',{x:b.x-3,y:b.y-3,width:b.w+6,height:b.h+6,class:'selectionBox'});ig.appendChild(r);if(m.locked)return;if(LINE_TYPES.includes(m.type)){[['start',m.x,m.y],['end',m.x2,m.y2]].forEach(([d,x,y])=>{const h=svgEl('circle',{cx:x,cy:y,r:4,class:'endpoint'});h.dataset.dir=d;h.addEventListener('pointerdown',e=>resizePointerDown(e,m,d));ig.appendChild(h)});return}const pts={nw:[b.x,b.y],n:[b.x+b.w/2,b.y],ne:[b.x+b.w,b.y],e:[b.x+b.w,b.y+b.h/2],se:[b.x+b.w,b.y+b.h],s:[b.x+b.w/2,b.y+b.h],sw:[b.x,b.y+b.h],w:[b.x,b.y+b.h/2]};Object.entries(pts).forEach(([d,[x,y]])=>{const h=svgEl('rect',{x:x-3,y:y-3,width:6,height:6,class:'handle'});h.dataset.dir=d;h.addEventListener('pointerdown',e=>resizePointerDown(e,m,d));ig.appendChild(h)})}
function svgPoint(e){const svg=$('#pageSvg'),pt=svg.createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;return pt.matrixTransform(svg.getScreenCTM().inverse())}
function translateMarkup(m,dx,dy,orig){if(LINE_TYPES.includes(m.type)){m.x=orig.x+dx;m.y=orig.y+dy;m.x2=orig.x2+dx;m.y2=orig.y2+dy}else if(POLY_TYPES.includes(m.type)){m.points=orig.points.map(([x,y])=>[x+dx,y+dy])}else if(m.type==='freehand'){m.points=orig.points.map(([x,y])=>[x+dx,y+dy]);rebuildFreehand(m)}else{m.x=orig.x+dx;m.y=orig.y+dy}}
function objectPointerDown(e,m){if(state.tool!=='select'||isMarkupLocked(m))return;e.stopPropagation();state.selected=m.id;state.propertyMode='object';renderSelection();updateProperties();const start=svgPoint(e),orig=JSON.parse(JSON.stringify(m));const move=ev=>{const q=svgPoint(ev);translateMarkup(m,q.x-start.x,q.y-start.y,orig);renderMarkups();if(state.editing===m.id)positionInlineEditor()};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);m.modified=new Date().toISOString();renderTable()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}
function resizePointerDown(e,m,dir){e.stopPropagation();e.preventDefault();const start=svgPoint(e),orig=JSON.parse(JSON.stringify(m)),ob=bounds(orig);const move=ev=>{const q=svgPoint(ev),dx=q.x-start.x,dy=q.y-start.y;if(LINE_TYPES.includes(m.type)){if(dir==='start'){m.x=orig.x+dx;m.y=orig.y+dy}else{m.x2=orig.x2+dx;m.y2=orig.y2+dy}}else{let nx=ob.x,ny=ob.y,nw=ob.w,nh=ob.h;if(dir.includes('e'))nw=Math.max(4,ob.w+dx);if(dir.includes('s'))nh=Math.max(4,ob.h+dy);if(dir.includes('w')){nx=Math.min(ob.x+ob.w-4,ob.x+dx);nw=Math.max(4,ob.w-dx)}if(dir.includes('n')){ny=Math.min(ob.y+ob.h-4,ob.y+dy);nh=Math.max(4,ob.h-dy)}applyBounds(m,orig,ob,{x:nx,y:ny,w:nw,h:nh})}renderMarkups();if(state.editing===m.id)positionInlineEditor()};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);m.modified=new Date().toISOString();renderTable()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}
function applyBounds(m,orig,ob,nb){if(POLY_TYPES.includes(m.type)||m.type==='freehand'){const sx=ob.w?nb.w/ob.w:1,sy=ob.h?nb.h/ob.h:1;m.points=orig.points.map(([x,y])=>[nb.x+(x-ob.x)*sx,nb.y+(y-ob.y)*sy]);if(m.type==='freehand')rebuildFreehand(m)}else{m.x=nb.x;m.y=nb.y;m.w=nb.w;m.h=nb.h}}
function rebuildFreehand(m){m.d=m.points.map((p,i)=>(i?'L':'M')+p[0]+' '+p[1]).join(' ');const xs=m.points.map(p=>p[0]),ys=m.points.map(p=>p[1]);m.bounds={x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...xs)-Math.min(...xs),h:Math.max(...ys)-Math.min(...ys)}}
function cloudRectPath(x,y,w,h){return cloudPolygonPath([[x,y],[x+w,y],[x+w,y+h],[x,y+h]])}
function cloudPolygonPath(points){if(!points?.length)return'';const pts=[...points,points[0]],r=10;let d=`M${points[0][0]} ${points[0][1]}`;for(let s=0;s<points.length;s++){const [x1,y1]=pts[s],[x2,y2]=pts[s+1],dx=x2-x1,dy=y2-y1,len=Math.max(1,Math.hypot(dx,dy)),n=Math.max(1,Math.round(len/r));for(let i=1;i<=n;i++){const t0=(i-1)/n,t1=i/n,mx=x1+dx*(t0+t1)/2,my=y1+dy*(t0+t1)/2,px=-dy/len,py=dx/len,bulge=Math.min(5,len/n*.35),ex=x1+dx*t1,ey=y1+dy*t1;d+=` Q${mx+px*bulge} ${my+py*bulge} ${ex} ${ey}`}}return d+' Z'}
function startZoomRect(e,start){const ig=$('#interactionLayer'),r=svgEl('rect',{class:'zoomRect'});ig.appendChild(r);const move=ev=>{const q=svgPoint(ev);r.setAttribute('x',Math.min(start.x,q.x));r.setAttribute('y',Math.min(start.y,q.y));r.setAttribute('width',Math.abs(q.x-start.x));r.setAttribute('height',Math.abs(q.y-start.y))};const up=ev=>{const q=svgPoint(ev),w=Math.abs(q.x-start.x),h=Math.abs(q.y-start.y);window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);if(w>5&&h>5){const a=$('#canvasScroller'),factor=Math.min((a.clientWidth-40)/(w*96/72),(a.clientHeight-40)/(h*96/72));setZoom(factor);requestAnimationFrame(()=>{const cx=(Math.min(start.x,q.x)+w/2)*96/72*state.zoom,cy=(Math.min(start.y,q.y)+h/2)*96/72*state.zoom;a.scrollLeft=Math.max(0,cx-a.clientWidth/2);a.scrollTop=Math.max(0,cy-a.clientHeight/2)})}renderMarkups();setTool('hand')};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}
function baseMarkup(type,p){return{id:uid(),type,x:p.x,y:p.y,x2:p.x,y2:p.y,w:1,h:1,d:'',layer:type==='measure'?'measurements':state.activeLayer,subject:toolLabel(type),comment:'',status:'Open',created:new Date().toISOString(),modified:new Date().toISOString(),...style()}}
$('#pageSvg').addEventListener('pointerdown',e=>{if(e.button!==0)return;const p=svgPoint(e);if(state.tool==='select'){if(e.target.closest?.('.markup'))return;state.selected=null;state.propertyMode='object';renderMarkups();updateProperties();return}if(['hand','textselect'].includes(state.tool)||POLY_TYPES.includes(state.tool))return;if(state.tool==='zoom'){startZoomRect(e,p);return}if(state.tool==='text'){const m={...baseMarkup('text',p),type:'text',w:170,h:28,width:0,stroke:'#111',fill:'#fff',fillOpacity:0,text:'',fontSize:state.preset.fontSize||14,textColor:state.preset.textColor||'#111'};addMarkup(m,false);editText(m);return}const m=baseMarkup(state.tool,p);if(state.tool==='highlight'){m.fill='#ffe000';m.fillOpacity=.4;m.stroke='none';m.width=0}if(state.tool==='hatch'){m.hatch=state.preset.hatch==='none'?'diag45':state.preset.hatch;m.fillOpacity=state.preset.fillOpacity??0}if(state.tool==='textbox'){m.text='';m.fill='#fff';m.fillOpacity=0;m.stroke='#111';m.width=1;m.fontSize=state.preset.fontSize||14;m.textColor=state.preset.textColor||'#111'}if(state.tool==='note'){m.text='';m.fill='#fff6b8';m.fillOpacity=.85;m.stroke='#555';m.width=1;m.fontSize=state.preset.fontSize||14;m.textColor='#111'}if(state.tool==='freehand'){m.points=[[p.x,p.y]];m.d=`M${p.x} ${p.y}`}currentPage().markups.push(m);state.drawing=m;const move=ev=>drawingMove(ev,m,p);const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);finishDrawing(m);state.drawing=null};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)});
function drawingMove(ev,m,start){const q=svgPoint(ev);if(LINE_TYPES.includes(m.type)){m.x2=q.x;m.y2=q.y}else if(m.type==='freehand'){m.points.push([q.x,q.y]);rebuildFreehand(m)}else{let w=Math.abs(q.x-start.x),h=Math.abs(q.y-start.y),x=Math.min(start.x,q.x),y=Math.min(start.y,q.y);if(['square','circle'].includes(m.type)){const z=Math.max(w,h);w=h=z;x=q.x<start.x?start.x-z:start.x;y=q.y<start.y?start.y-z:start.y}m.x=x;m.y=y;m.w=w;m.h=h}renderMarkups()}
function finishDrawing(m){const b=bounds(m);if(b&&b.w<2&&b.h<2&&!LINE_TYPES.includes(m.type)&&m.type!=='freehand'){currentPage().markups=currentPage().markups.filter(x=>x!==m);render();return}state.selected=m.id;state.propertyMode='object';render();setTool('select');if(['textbox','note'].includes(m.type))editText(m)}
$('#pageSvg').addEventListener('click',e=>{if(!POLY_TYPES.includes(state.tool)||e.detail>1)return;const p=svgPoint(e);if(!state.polyDraft){const m=baseMarkup(state.tool,p);m.points=[[p.x,p.y]];if(state.tool==='hatchFree')m.hatch=state.preset.hatch==='none'?'diag45':state.preset.hatch;if(state.tool==='cloudFree'){m.fill='#fff';m.fillOpacity=0}currentPage().markups.push(m);state.polyDraft=m}else state.polyDraft.points.push([p.x,p.y]);renderMarkups()});
$('#pageSvg').addEventListener('dblclick',e=>{if(!POLY_TYPES.includes(state.tool))return;e.preventDefault();finishPolyDraft(true)});
function finishPolyDraft(select=true){const m=state.polyDraft;if(!m)return;if(m.points.length>1){const a=m.points.at(-1),b=m.points.at(-2);if(Math.hypot(a[0]-b[0],a[1]-b[1])<5)m.points.pop()}const need=m.type==='polyline'?2:3;if(m.points.length<need)currentPage().markups=currentPage().markups.filter(x=>x!==m);else if(select){state.selected=m.id;m.modified=new Date().toISOString()}state.polyDraft=null;render();if(select)setTool('select')}
function addMarkup(obj,select=true){obj.id=obj.id||uid();obj.layer=obj.layer||state.activeLayer||'default';obj.created=obj.created||new Date().toISOString();obj.modified=new Date().toISOString();obj.status=obj.status||'Open';currentPage().markups.push(obj);if(select){state.selected=obj.id;state.propertyMode='object'}render();if(select)setTool('select')}
function editText(m){if(!m||!TEXT_TYPES.includes(m.type)||isMarkupLocked(m))return;state.selected=m.id;state.editing=m.id;state.tool='select';renderMarkups();const ed=$('#inlineEditor');ed.value=m.text||'';ed.classList.remove('hidden');positionInlineEditor();ed.focus();ed.setSelectionRange(ed.value.length,ed.value.length)}
function positionInlineEditor(){const m=selectedMarkup();if(!m||state.editing!==m.id)return;const ed=$('#inlineEditor'),s=96/72*state.zoom;ed.style.left=m.x*s+'px';ed.style.top=m.y*s+'px';ed.style.width=Math.max(30,m.w*s)+'px';ed.style.height=Math.max(20,m.h*s)+'px';ed.style.fontFamily=m.font||'Arial';ed.style.fontSize=(m.fontSize||14)*s+'px';ed.style.fontWeight=m.bold?'700':'400';ed.style.fontStyle=m.italic?'italic':'normal';ed.style.color=m.textColor||'#111';ed.style.textAlign=m.textAlign||'left';ed.style.background=colorWithAlpha(m.fill||'#fff',m.fillOpacity??0)}
function colorWithAlpha(hex,a){if(!/^#[0-9a-f]{6}$/i.test(hex))return'rgba(255,255,255,.8)';const n=parseInt(hex.slice(1),16);return`rgba(${n>>16},${n>>8&255},${n&255},${Math.max(.08,a)})`}
$('#inlineEditor').addEventListener('input',e=>{const m=selectedMarkup();if(m&&state.editing===m.id){m.text=e.target.value;m.modified=new Date().toISOString()}});$('#inlineEditor').addEventListener('blur',finishInlineEdit);$('#inlineEditor').addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();finishInlineEdit()}e.stopPropagation()});function finishInlineEdit(){const m=selectedMarkup(),ed=$('#inlineEditor');if(m&&state.editing===m.id)m.text=ed.value;state.editing=null;ed.classList.add('hidden');renderMarkups();renderTable()}
function addStamp(text){addMarkup({type:'stamp',x:60,y:60,w:190,h:44,text,subject:text,comment:'',status:'Open',stroke:text.startsWith('TTC')?'#d66b12':(text.includes('SIGNAL')||text.startsWith('SIGN ')?'#1b5fa6':'#b5252b'),width:2,fill:'#fff',fillOpacity:1,dash:'',hatch:'none',hatchColor:'#000',hatchSpacing:10,opacity:1,rotation:0})}
function addTrafficSign(s){const b=viewportCenterOnPage(),size=58;addMarkup({type:'trafficSign',layer:'traffic',x:b.x-size/2,y:b.y-size/2,w:size,h:size,subject:`${s.code} ${s.name}`,comment:s.source||'',status:'Open',signCode:s.code,signName:s.name,signShape:s.shape,signBg:s.background,showCode:true,stroke:'#222',width:1,fill:'#fff',fillOpacity:1,dash:'',hatch:'none',opacity:1,rotation:0})}
function addTrafficDevice(d){const b=viewportCenterOnPage();if(['workZone','buffer'].includes(d.kind)){addMarkup({type:'hatch',layer:'traffic',x:b.x-90,y:b.y-45,w:180,h:90,subject:d.name,comment:'TxDOT temporary traffic control plan element',status:'Open',stroke:d.kind==='workZone'?'#d71920':'#1267b1',width:2,fill:'#fff',fillOpacity:.05,dash:d.kind==='buffer'?'8 5':'',hatch:d.kind==='workZone'?'diag45':'none',hatchColor:'#d71920',hatchSpacing:12,opacity:1});return}addMarkup({type:'device',layer:'traffic',x:b.x-18,y:b.y-25,w:36,h:50,deviceKind:d.kind,deviceCode:d.code,subject:d.name,comment:'TxDOT / TMUTCD traffic-control device',status:'Open',stroke:'#222',width:1,fill:'#fff',fillOpacity:1,dash:'',hatch:'none',opacity:1,rotation:0})}
function addStandardNote(s){const b=viewportCenterOnPage();addMarkup({type:'note',layer:'traffic',x:b.x-130,y:b.y-40,w:260,h:80,text:`${s.code}\n${s.name}${s.detail?'\n'+s.detail:''}`,subject:`TxDOT Standard ${s.code}`,comment:'Reference the current TxDOT Traffic Standards file before final use.',status:'Open',stroke:'#1267b1',width:1,fill:'#eaf5ff',fillOpacity:.95,hatch:'none',opacity:1,font:'Arial',fontSize:11,textColor:'#0b3f6d',textAlign:'left'})}
function viewportCenterOnPage(){const sc=$('#canvasScroller'),s=96/72*state.zoom;return{x:(sc.scrollLeft+sc.clientWidth/2)/s,y:(sc.scrollTop+sc.clientHeight/2)/s}}
function renderPages(){const box=$('#pageThumbs');box.innerHTML='';state.pages.forEach((p,i)=>{const b=document.createElement('button');b.className='pageThumb'+(i===state.pageIndex?' active':'');b.innerHTML=`<span class="thumbSheet" style="aspect-ratio:${p.w}/${p.h}"></span><span><strong>Page ${i+1}</strong><br>${esc(p.name)}</span>`;b.onclick=()=>{state.pageIndex=i;state.selected=null;render();fitPage()};box.appendChild(b)})}
function renderTable(){const rows=$('#markupRows'),filter=($('#markupFilter')?.value||'').toLowerCase();rows.innerHTML='';let n=0;state.pages.forEach((p,pi)=>p.markups.forEach(m=>{if(filter&&!(`${m.subject} ${m.comment} ${m.status}`.toLowerCase().includes(filter)))return;n++;const tr=document.createElement('tr');if(m.id===state.selected&&pi===state.pageIndex)tr.classList.add('selected');tr.innerHTML=`<td>${pi+1}</td><td>${esc(m.subject||toolLabel(m.type))}</td><td>${esc(m.status||'Open')}</td><td>${esc(m.comment||'')}</td><td>${new Date(m.modified||m.created).toLocaleString()}</td>`;tr.onclick=()=>{state.pageIndex=pi;state.selected=m.id;state.propertyMode='object';render()};rows.appendChild(tr)}));$('#markupCount').textContent=`${n} markup${n===1?'':'s'}`}
function propertyTarget(){if(state.propertyMode==='tool')return state.preset;return selectedMarkup()}
function isTextTarget(t){if(state.propertyMode==='tool')return TEXT_TYPES.includes(state.propertyTool);return t&&TEXT_TYPES.includes(t.type)}
function updateProperties(){const t=propertyTarget(),empty=!t;$('#propEmpty').classList.toggle('hidden',!empty);$('#propEditor').classList.toggle('hidden',empty);$('#propTitle').textContent=state.propertyMode==='tool'?`${toolLabel(state.propertyTool)} Defaults`:'Properties';$('#propHint').textContent=state.propertyMode==='tool'?'applies to newly drawn objects':(selectedMarkup()?.subject||'');if(!t)return;$('#propSubject').value=t.subject||'';$('#propStatus').value=t.status||'Open';$('#propComment').value=t.comment||'';$('#propStroke').value=validColor(t.stroke)?t.stroke:'#000000';$('#propWidth').value=t.width??2;$('#propFill').value=validColor(t.fill)?t.fill:'#ffffff';$('#propFillOpacity').value=t.fillOpacity??0;$('#propDash').value=t.dash||'';$('#propHatch').value=t.hatch||'none';$('#propHatchColor').value=validColor(t.hatchColor)?t.hatchColor:(validColor(t.stroke)?t.stroke:'#000000');$('#propHatchSpacing').value=t.hatchSpacing??10;$('#propOpacity').value=t.opacity??1;$('#propRotation').value=t.rotation||0;$('#propFont').value=t.font||'Arial';$('#propFontSize').value=t.fontSize||14;$('#propTextColor').value=validColor(t.textColor)?t.textColor:'#111111';$('#propTextAlign').value=t.textAlign||'left';$('#propBold').checked=!!t.bold;$('#propItalic').checked=!!t.italic;const layerSel=$('#propLayer');layerSel.innerHTML=state.layers.map(l=>`<option value="${esc(l.id)}">${esc(l.name)}</option>`).join('');layerSel.value=t.layer||state.activeLayer||'default';$('#textProps').classList.toggle('hidden',!isTextTarget(t));const objectOnly=state.propertyMode==='object';$('#propSubject').disabled=!objectOnly;$('#propStatus').disabled=!objectOnly;$('#propComment').disabled=!objectOnly;$('#duplicateObj').disabled=!objectOnly;$('#deleteObj').disabled=!objectOnly;$('#propLayer').disabled=!objectOnly}
function validColor(c){return /^#[0-9a-f]{6}$/i.test(c||'')}
function bindProp(id,key,evt='input',conv=v=>v){$(id).addEventListener(evt,e=>{const t=propertyTarget();if(!t)return;t[key]=conv(e.target.type==='checkbox'?e.target.checked:e.target.value);if(state.propertyMode==='object')t.modified=new Date().toISOString();renderMarkups();renderTable();if(state.editing)positionInlineEditor()})}
bindProp('#propSubject','subject');bindProp('#propStatus','status','change');bindProp('#propComment','comment');bindProp('#propStroke','stroke');bindProp('#propWidth','width','input',Number);bindProp('#propFill','fill');bindProp('#propFillOpacity','fillOpacity','input',Number);bindProp('#propDash','dash','change');bindProp('#propHatch','hatch','change');bindProp('#propHatchColor','hatchColor');bindProp('#propHatchSpacing','hatchSpacing','input',Number);bindProp('#propOpacity','opacity','input',Number);bindProp('#propRotation','rotation','input',Number);bindProp('#propFont','font','change');bindProp('#propFontSize','fontSize','input',Number);bindProp('#propTextColor','textColor');bindProp('#propTextAlign','textAlign','change');bindProp('#propBold','bold','change',Boolean);bindProp('#propItalic','italic','change',Boolean);bindProp('#propLayer','layer','change');
function duplicateSelected(){const m=selectedMarkup();if(!m)return;const c=JSON.parse(JSON.stringify(m)),orig=JSON.parse(JSON.stringify(m));c.id=uid();translateMarkup(c,12,12,orig);c.subject=(c.subject||'Markup')+' Copy';c.modified=new Date().toISOString();currentPage().markups.push(c);state.selected=c.id;render()}
function deleteSelected(){if(!state.selected)return;currentPage().markups=currentPage().markups.filter(x=>x.id!==state.selected);state.selected=null;finishInlineEdit();render()}
$('#duplicateObj').onclick=duplicateSelected;$('#deleteObj').onclick=deleteSelected;$('#savePreset').onclick=()=>{const m=selectedMarkup();if(m){copyAppearanceToPreset(m);toast('Appearance copied to current drawing defaults.')}else toast('Current tool defaults are already active.')};
function copyAppearanceToPreset(m){['stroke','width','fill','fillOpacity','dash','hatch','hatchColor','hatchSpacing','opacity','font','fontSize','textColor','textAlign','bold','italic'].forEach(k=>{if(m[k]!==undefined)state.preset[k]=m[k]})}
function openContext(e,id){e.preventDefault();e.stopPropagation();state.selected=id;state.propertyMode='object';renderMarkups();updateProperties();const cm=$('#contextMenu'),m=selectedMarkup();$$('#contextMenu .textOnly').forEach(x=>x.classList.toggle('hidden',!TEXT_TYPES.includes(m?.type)));cm.style.left=Math.min(e.clientX,window.innerWidth-180)+'px';cm.style.top=Math.min(e.clientY,window.innerHeight-230)+'px';cm.classList.remove('hidden')}
$('#contextMenu').addEventListener('click',e=>{const cmd=e.target.dataset.cmd;if(!cmd)return;const p=currentPage(),i=p.markups.findIndex(x=>x.id===state.selected),m=p.markups[i];if(cmd==='properties'){openPropertiesAt(null,'object')}else if(cmd==='editText'&&m)editText(m);else if(cmd==='duplicate')duplicateSelected();else if(cmd==='delete')deleteSelected();else if(cmd==='front'&&i>=0){p.markups.push(p.markups.splice(i,1)[0]);render()}else if(cmd==='back'&&i>=0){p.markups.unshift(p.markups.splice(i,1)[0]);render()}else if(cmd==='lock'&&m){m.locked=!m.locked;toast(m.locked?'Object locked':'Object unlocked');renderSelection()}else if(cmd==='preset'&&m){copyAppearanceToPreset(m);toast('Appearance copied to drawing defaults.')}$('#contextMenu').classList.add('hidden')});
function openPropertiesAt(point,mode='object',tool=null){state.propertyMode=mode;if(tool)state.propertyTool=tool;closePalettes('propertiesPalette');const p=$('#propertiesPalette');p.classList.remove('hidden');if(point&&window.innerWidth>620){p.style.left='auto';p.style.right=Math.max(6,window.innerWidth-point.x-20)+'px';p.style.top=Math.max(78,Math.min(point.y,window.innerHeight-p.offsetHeight-10))+'px'}else{p.style.left='';p.style.right='8px';p.style.top='80px'}updateProperties()}
function closePalettes(except){$$('.palette').forEach(p=>{if(p.id!==except)p.classList.add('hidden')})}
function togglePalette(id){const p=$('#'+id),opening=p.classList.contains('hidden');closePalettes(opening?id:null);p.classList.toggle('hidden',!opening);if(id==='propertiesPalette')updateProperties();if(id==='layersPalette')renderLayers();if(id==='trafficPalette')renderTrafficLibrary();if(id==='markupsPalette')renderTable()}
$$('[data-palette]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();togglePalette(b.dataset.palette)}));$$('[data-close]').forEach(b=>b.onclick=e=>{e.stopPropagation();b.closest('.palette').classList.add('hidden')});$('#btnProperties').onclick=e=>{e.stopPropagation();if(selectedMarkup())openPropertiesAt(null,'object');else openPropertiesAt(null,'tool',state.tool)};
$$('[data-tool]').forEach(b=>{b.addEventListener('click',()=>setTool(b.dataset.tool));b.addEventListener('contextmenu',e=>{e.preventDefault();e.stopPropagation();setTool(b.dataset.tool);openPropertiesAt({x:e.clientX,y:e.clientY},'tool',b.dataset.tool)})});
$$('[data-preset]').forEach(b=>b.onclick=()=>{if(b.dataset.preset==='reviewRed')Object.assign(state.preset,{stroke:'#d71920',width:2,fill:'#fff',fillOpacity:0,dash:'',hatch:'none',opacity:1});if(b.dataset.preset==='inspectionBlue')Object.assign(state.preset,{stroke:'#0066cc',width:2,fill:'#fff',fillOpacity:0,dash:'',hatch:'none',opacity:1});if(b.dataset.preset==='yellowHighlight')Object.assign(state.preset,{stroke:'#f3c000',width:1,fill:'#ffe000',fillOpacity:.45,dash:'',hatch:'none',opacity:.8});toast('Drawing default updated.')});
function renderLayers(){const box=$('#layerList');if(!box)return;box.innerHTML='';state.layers.forEach(l=>{const row=document.createElement('div');row.className='layerRow';const active=document.createElement('button');active.className=l.id===state.activeLayer?'activeLayer':'';active.textContent=l.id===state.activeLayer?'●':'○';active.title='Make active layer';active.onclick=()=>{state.activeLayer=l.id;renderLayers()};const vis=document.createElement('button');vis.textContent=l.visible===false?'◌':'◉';vis.title=l.visible===false?'Show layer':'Hide layer';vis.onclick=()=>{l.visible=l.visible===false?true:false;if(state.selected&&!isMarkupVisible(selectedMarkup()||{}))state.selected=null;render()};const lock=document.createElement('button');lock.textContent=l.locked?'🔒':'🔓';lock.title=l.locked?'Unlock layer':'Lock layer';lock.onclick=()=>{l.locked=!l.locked;renderLayers();renderSelection()};const name=document.createElement('span');name.className='layerName';name.textContent=l.name;row.append(active,vis,lock,name);box.appendChild(row)});updateProperties()}
$('#addLayer').onclick=()=>{let base='Layer',n=1;while(state.layers.some(l=>l.name===`${base} ${n}`))n++;const id='layer_'+Date.now().toString(36);state.layers.push({id,name:`${base} ${n}`,visible:true,locked:false});state.activeLayer=id;renderLayers();toast(`Created ${base} ${n}.`)};
function fillStamps(id,list,cls=''){const box=$(id);box.innerHTML='';list.forEach(t=>{const b=document.createElement('button');b.className='stampBtn '+cls;b.textContent=t;b.onclick=()=>addStamp(t);box.appendChild(b)})}fillStamps('#stampsInspection',inspection);fillStamps('#stampsSignals',signals,'blue');fillStamps('#stampsSigns',signs,'blue');fillStamps('#stampsTtc',ttc,'orange');
function renderCustomStamps(){const box=$('#stampsCustom');box.innerHTML='';state.customStamps.forEach(s=>{const b=document.createElement('button');b.className='stampBtn customStampBtn';b.innerHTML=`<img src="${s.data}" alt="${esc(s.name)}"><span>${esc(s.name)}</span>`;b.onclick=()=>addStamp(s.name.replace(/\.[^.]+$/,''));box.appendChild(b)})}try{state.customStamps=JSON.parse(localStorage.getItem('nxt_custom_stamps')||'[]')}catch{}renderCustomStamps();
$('#addCustomStamp').onclick=()=>$('#stampOpen').click();$('#stampOpen').onchange=async e=>{const f=e.target.files[0];if(!f)return;state.customStamps.push({name:f.name,data:await fileDataUrl(f)});localStorage.setItem('nxt_custom_stamps',JSON.stringify(state.customStamps));renderCustomStamps();toast('Custom stamp added to local library.')};
function trafficPreview(s){const cls=s.shape==='diamond'?'diamond '+(s.background==='orange'?'orange':''):s.shape==='octagon'?'octagon':s.shape==='triangle'?'triangle':'rectangle '+(s.background==='green'?'green':s.background==='blue'?'blue':'');const text=(s.shape==='octagon'?'STOP':s.shape==='triangle'?'YIELD':s.name).split(/\s+/).slice(0,4).join(' ');return`<div class="trafficSignPreview"><div class="face ${cls}"><span>${esc(text)}</span></div></div>`}
function renderTrafficLibrary(){const q=($('#trafficSearch').value||'').trim().toLowerCase(),cat=$('#trafficCategory').value,box=$('#trafficResults');box.innerHTML='';let items=[];MUTCD_SIGNS.forEach(s=>items.push({...s,itemKind:'sign'}));TEXAS_SIGNS.forEach(s=>items.push({...s,itemKind:'sign'}));TRAFFIC_DEVICES.forEach(s=>items.push({...s,category:'devices',itemKind:'device',source:'2025 TMUTCD Part 6 / TxDOT work-zone standards'}));TXDOT_STANDARDS.forEach(s=>items.push({...s,category:'standards',itemKind:'standard',source:'Current TxDOT Traffic Standards'}));items=items.filter(s=>(cat==='all'||s.category===cat)&&(!q||`${s.code} ${s.name} ${s.source||''} ${s.group||''}`.toLowerCase().includes(q)));items.forEach(s=>{const b=document.createElement('button');if(s.itemKind==='sign'){b.className='trafficCard';b.innerHTML=trafficPreview(s)+`<span class="trafficMeta"><b>${esc(s.code)}</b><strong>${esc(s.name)}</strong><small>${esc(s.source||'')}</small></span>`;b.onclick=()=>addTrafficSign(s)}else if(s.itemKind==='device'){const glyph={cone:'▲',drum:'▥',verticalPanel:'▯',barricade:'☷',barrier:'▰',arrowBoard:'⇢',pcms:'▣',tma:'▱',flagger:'⚑',workVehicle:'▣',trafficFlow:'➜',workZone:'▧',buffer:'⋯'}[s.kind]||'◆';b.className='trafficCard deviceCard';b.innerHTML=`<span class="deviceGlyph">${glyph}</span><span class="trafficMeta"><b>${esc(s.code)}</b><strong>${esc(s.name)}</strong><small>${esc(s.source)}</small></span>`;b.onclick=()=>addTrafficDevice(s)}else{b.className='trafficCard standardCard';b.innerHTML=`<span class="trafficMeta"><b>${esc(s.code)}</b><strong>${esc(s.name)}</strong><small>${esc(s.detail||s.source||'')}</small></span>`;b.onclick=()=>addStandardNote(s)}box.appendChild(b)});const foot=document.createElement('div');foot.className='trafficMore';foot.textContent=`${items.length} matching reference item${items.length===1?'':'s'} · click an item to place a plan-reference object`;box.appendChild(foot)}
$('#trafficSearch').oninput=renderTrafficLibrary;$('#trafficCategory').onchange=renderTrafficLibrary;
HATCH_LIBRARY.forEach(h=>{const o=document.createElement('option');o.value=h.id;o.textContent=`${h.family} — ${h.name}`;$('#propHatch').appendChild(o)});const none=document.createElement('option');none.value='none';none.textContent='None';$('#propHatch').insertBefore(none,$('#propHatch').firstChild);
$('#newPage').onclick=()=>$('#modalBackdrop').classList.remove('hidden');$('#cancelModal').onclick=()=>$('#modalBackdrop').classList.add('hidden');$('#createPage').onclick=()=>{const [w,h,name]=$('#sheetSize').value.split(',');state.pages.push(newPage(+w,+h,name));state.pageIndex=state.pages.length-1;state.selected=null;$('#modalBackdrop').classList.add('hidden');render();fitPage()};
$('#importImage').onclick=()=>$('#imageOpen').click();$('#imageOpen').onchange=async e=>{const f=e.target.files[0];if(!f)return;const data=await fileDataUrl(f),img=new Image();img.onload=()=>{const landscape=img.width>=img.height,p=newPage(landscape?792:612,landscape?612:792,'Imported Image');p.bg={data,name:f.name};state.pages.push(p);state.pageIndex=state.pages.length-1;render();fitPage()};img.src=data};
function fileDataUrl(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)})}
$('#btnOpen').onclick=()=>$('#fileOpen').click();$('#fileOpen').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.name.toLowerCase().endsWith('.nxp')){loadProject(JSON.parse(await f.text()));return}if(f.type==='application/pdf'||f.name.toLowerCase().endsWith('.pdf')){const url=URL.createObjectURL(f);state.pdfMode=true;$('#pdfFrame').src=url+'#toolbar=1&navpanes=0&view=FitH';$('#pdfFrame').classList.remove('hidden');$('#pdfNotice').classList.remove('hidden');$('#canvasScroller').classList.add('hidden');state.projectName=f.name;$('#docTitle').textContent=f.name;closePalettes();setTool('hand');toast('Opened PDF in native-view mode.');return}if(f.type.startsWith('image/')){$('#imageOpen').files=e.target.files;$('#imageOpen').dispatchEvent(new Event('change'))}};$('#closePdfMode').onclick=()=>{state.pdfMode=false;$('#pdfFrame').classList.add('hidden');$('#pdfNotice').classList.add('hidden');$('#canvasScroller').classList.remove('hidden');setTool('hand');fitPage()};
$('#btnSaveProject').onclick=()=>{const data={format:'NXT Gen Plans Project',version:'0.1-R2',projectName:state.projectName,pages:state.pages,preset:state.preset,layers:state.layers,activeLayer:state.activeLayer};download(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),(state.projectName.replace(/\.pdf$/i,'')||'NXT_Gen_Plans')+'.nxp')};function loadProject(d){if(!d||!Array.isArray(d.pages))return toast('Not a valid NXT project file.');state.pages=d.pages;state.projectName=d.projectName||'NXT Gen Plans';state.preset={...state.preset,...(d.preset||{})};if(Array.isArray(d.layers)&&d.layers.length)state.layers=d.layers;state.activeLayer=d.activeLayer||state.layers[0]?.id||'default';state.pageIndex=0;state.selected=null;state.pdfMode=false;$('#pdfFrame').classList.add('hidden');$('#pdfNotice').classList.add('hidden');$('#canvasScroller').classList.remove('hidden');render();fitPage();toast('Project loaded.')}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1200)}
$('#btnExportPdf').onclick=async()=>{if(state.pdfMode)return toast('0.1 PDF export supports NXT plan-canvas pages. Imported-PDF annotation/export requires the next PDF-engine checkpoint.');finishInlineEdit();toast('Rendering flattened Adobe-compatible PDF…');try{const pages=[];for(let i=0;i<state.pages.length;i++)pages.push(await rasterPage(i));download(new Blob([buildPdf(pages)],{type:'application/pdf'}),(state.projectName.replace(/\.[^.]+$/,'')||'NXT_Gen_Plans')+'_review.pdf');toast('PDF exported.')}catch(err){console.error(err);toast('PDF export failed: '+err.message)}};
async function rasterPage(i){const prev=state.pageIndex,sel=state.selected;state.pageIndex=i;state.selected=null;render();await new Promise(r=>setTimeout(r,25));const p=currentPage(),svg=$('#pageSvg').cloneNode(true);svg.querySelector('#interactionLayer').innerHTML='';svg.setAttribute('width',p.w*2);svg.setAttribute('height',p.h*2);const xml=new XMLSerializer().serializeToString(svg),blob=new Blob([xml],{type:'image/svg+xml'}),url=URL.createObjectURL(blob),img=new Image();await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=url});const c=document.createElement('canvas');c.width=Math.round(p.w*2);c.height=Math.round(p.h*2);const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);const jpg=base64Bytes(c.toDataURL('image/jpeg',.94).split(',')[1]);state.pageIndex=prev;state.selected=sel;render();return{w:p.w,h:p.h,jpg,iw:c.width,ih:c.height}}
function base64Bytes(s){const bin=atob(s),a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return a}
function buildPdf(pages){const enc=new TextEncoder(),parts=[],offsets=[0];let len=0;const push=x=>{const b=typeof x==='string'?enc.encode(x):x;parts.push(b);len+=b.length};push('%PDF-1.7\n%âãÏÓ\n');const objects=[];objects[1]='<< /Type /Catalog /Pages 2 0 R >>';const kids=[];let obj=3;for(const p of pages){const pageObj=obj++,contentObj=obj++,imgObj=obj++;kids.push(`${pageObj} 0 R`);objects[pageObj]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${p.w} ${p.h}] /Resources << /XObject << /Im0 ${imgObj} 0 R >> >> /Contents ${contentObj} 0 R >>`;const stream=`q\n${p.w} 0 0 ${p.h} 0 0 cm\n/Im0 Do\nQ\n`;objects[contentObj]={dict:`<< /Length ${enc.encode(stream).length} >>`,stream:enc.encode(stream)};objects[imgObj]={dict:`<< /Type /XObject /Subtype /Image /Width ${p.iw} /Height ${p.ih} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${p.jpg.length} >>`,stream:p.jpg}}objects[2]=`<< /Type /Pages /Kids [${kids.join(' ')}] /Count ${pages.length} >>`;for(let i=1;i<objects.length;i++){offsets[i]=len;push(`${i} 0 obj\n`);const o=objects[i];if(typeof o==='string')push(o+'\nendobj\n');else{push(o.dict+'\nstream\n');push(o.stream);push('\nendstream\nendobj\n')}}const xref=len;push(`xref\n0 ${objects.length}\n0000000000 65535 f \n`);for(let i=1;i<objects.length;i++)push(String(offsets[i]).padStart(10,'0')+' 00000 n \n');push(`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`);const out=new Uint8Array(len);let pos=0;for(const b of parts){out.set(b,pos);pos+=b.length}return out}
function setZoom(z){state.zoom=Math.max(.05,Math.min(8,z));const zt=Math.round(state.zoom*100)+'%';$('#zoomSelect').value=[...$('#zoomSelect').options].some(o=>o.value===zt)?zt:'';render()}
function fitPage(){if(state.pdfMode)return;const p=currentPage(),a=$('#canvasScroller');setZoom(Math.min((a.clientWidth-55)/(p.w*96/72),(a.clientHeight-55)/(p.h*96/72)))}function fitWidth(){if(state.pdfMode)return;const p=currentPage(),a=$('#canvasScroller');setZoom((a.clientWidth-45)/(p.w*96/72))}
$('#zoomIn').onclick=()=>setZoom(state.zoom*1.25);$('#zoomOut').onclick=()=>setZoom(state.zoom/1.25);$('#fitPage').onclick=fitPage;$('#fitWidth').onclick=fitWidth;$('#actualSize').onclick=()=>setZoom(1);$('#zoomSelect').onchange=e=>{const n=parseFloat(e.target.value);if(n)setZoom(n/100)};
const sc=$('#canvasScroller');sc.addEventListener('pointerdown',e=>{if(state.tool!=='hand'||e.button!==0)return;state.pan={x:e.clientX,y:e.clientY,l:sc.scrollLeft,t:sc.scrollTop};sc.classList.add('panning');e.preventDefault()});window.addEventListener('pointermove',e=>{if(!state.pan)return;sc.scrollLeft=state.pan.l-(e.clientX-state.pan.x);sc.scrollTop=state.pan.t-(e.clientY-state.pan.y)});window.addEventListener('pointerup',()=>{state.pan=null;sc.classList.remove('panning')});sc.addEventListener('wheel',e=>{if(e.ctrlKey){e.preventDefault();const old=state.zoom;setZoom(state.zoom*(e.deltaY<0?1.12:.89));const ratio=state.zoom/old;sc.scrollLeft=(sc.scrollLeft+e.offsetX)*ratio-e.offsetX;sc.scrollTop=(sc.scrollTop+e.offsetY)*ratio-e.offsetY}},{passive:false});
function updateStatus(){const p=currentPage();$('#statusPage').textContent=`Page ${state.pageIndex+1} / ${state.pages.length}`;$('#statusSize').textContent=p.name;$('#statusZoom').textContent=Math.round(state.zoom*100)+'%';$('#docTitle').textContent=state.projectName}
$('#markupFilter').oninput=renderTable;
document.addEventListener('pointerdown',e=>{if(e.target.closest('.palette,.contextMenu,[data-palette],#btnProperties,#mainToolbar'))return;closePalettes();$('#contextMenu').classList.add('hidden')});document.addEventListener('click',e=>{if(!e.target.closest('#contextMenu'))$('#contextMenu').classList.add('hidden')});
window.addEventListener('keydown',e=>{const tag=document.activeElement?.tagName;if(['INPUT','TEXTAREA','SELECT'].includes(tag)&&document.activeElement!==$('#inlineEditor'))return;if(e.code==='Space'&&!e.repeat&&!state.editing){state.previousTool=state.tool;setTool('hand');e.preventDefault()}if(e.ctrlKey&&(e.key==='='||e.key==='+')){setZoom(state.zoom*1.25);e.preventDefault()}else if(e.ctrlKey&&e.key==='-'){setZoom(state.zoom/1.25);e.preventDefault()}else if(e.ctrlKey&&e.key==='0'){fitPage();e.preventDefault()}else if(e.ctrlKey&&e.key==='1'){setZoom(1);e.preventDefault()}else if(e.ctrlKey&&e.key==='2'){fitWidth();e.preventDefault()}else if(!e.ctrlKey&&!e.altKey&&!state.editing){if(e.key.toLowerCase()==='h')setTool('hand');if(e.key.toLowerCase()==='v')setTool('select');if(e.key.toLowerCase()==='z')setTool('zoom')}if(e.key==='Escape'){if(state.editing)finishInlineEdit();else{closePalettes();$('#contextMenu').classList.add('hidden');finishPolyDraft(false);setTool('hand')}}if(e.key==='Delete'&&state.selected&&!state.editing)deleteSelected()});window.addEventListener('keyup',e=>{if(e.code==='Space'&&state.previousTool){const t=state.previousTool;state.previousTool=null;setTool(t)}});window.addEventListener('resize',()=>{closePalettes();requestAnimationFrame(()=>state.pdfMode?null:fitPage())});
renderTrafficLibrary();render();requestAnimationFrame(fitPage);setTool('hand');closePalettes();
